CATROID-570 Refactor DeleteItemOfUserListActionTest to Kotlin
Catrobat/Catroid pull request #3733
Opened 2020-08-05 10:23 UTC by trummerp

- Refactored DeleteItemOfUserListActionTest to Kotlin
- Added some tests
- Reworked some tests
- Fixed a bug in DeleteItemOfUserListAction, where invalid parameter caused a deletion of the first element

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-08 02:53 UTC, ndrnour commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
> +    private var collection: ArrayList<Any>? = null
please change `action, userList, collection` to `lateinit var` and remove not-null assertion operators `!!` from your code

2020-08-08 02:56 UTC, ndrnour commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
> +        collection = ArrayList(listOf(1.0, "2.0", "test", 4.0))
change to `collection = arrayListOf(1.0, "2.0", "test", 4.0)`

2020-08-08 02:57 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/content/actions/DeleteItemOfUserListAction.kt
> +            formulaIndexToDelete?.interpretInteger(sprite)?.minus(1) ?: -1
👍🏼

2020-08-08 03:00 UTC, ndrnour commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
> +    @Throws(Exception::class)
is this really needed? `@Throws(Exception::class)`

2020-08-19 23:45 UTC, ndrnour requested changes
last modification. 💯

2020-08-26 15:20 UTC, Koell approved these changes
Thanks

2020-09-12 13:50 UTC, wslany commented
> last modification. 💯

Has this been resolved? If so, can you add your approval?

2020-09-13 09:33 UTC, wslany requested changes
Thanks. However, the tests in Java were more comprehensive: they tested, e.g., also whether the _intended_ elements were deleted, whereas in the new tests in Kotlin, you test only if the number of elements is correct. It could be that the order of deletion uses the indices in reverse, or is somehow random, and these tests would still be green, whereas the old test suite in Java would have caught that.

Having said that, it is anyway necessary to add a CLT for this brick, and then the more complex tests can be relegated there. Please add such a CLT for the brick in https://github.com/Catrobat/Catroid/tree/develop/catroid/src/androidTest/assets/catrobatTests/data instead of adding them to the Kotlin test. And please also add the test cases from the Kotlin tests to the CLTs. 

We want to use the CLTs as a formal, executable, but device independent specification in the form of automatic tests of the Catrobat language. Catty and other projects will be able to execute them, and any future implementation can use them as a reference against which to implement it.

2020-09-13 09:33 UTC, wslany commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
> +            arrayOf("NUMBER_NEGATIVE", listOf(Formula(-1)), 4),
```suggestion
            arrayOf("NUMBER_NEGATIVE", listOf(Formula(-1)), 4),
            arrayOf("NUMBER_TOO_LARGE", listOf(Formula(5)), 4),
```

Missing case.

2020-09-15 19:28 UTC, trummerp commented
Update: 
- Added missing case to the kotlin testcases
- Added a CLT including all possible kotlin testcases, as well as one for the deletion order

2020-11-24 10:52 UTC, gPathpp requested changes
PLEASE-ADD: a JUNIT test that verifies that the right index was deleted.
Also, perform a rebase, please.

2020-11-24 10:52 UTC, gPathpp commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
> +    private val deleteList: List<Formula?>?,
```suggestion
    private val deleteList: List<Formula?>,
```

2020-11-24 10:52 UTC, gPathpp commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/DeleteItemOfUserListActionTest.kt
> +        for (idx in deleteList!!) {
```suggestion
        for (idx in deleteList) {
```

2020-12-17 08:54 UTC, closed without merging