CATROID-629 Add sensors for text recognition
Catrobat/Catroid pull request #3734
Opened 2020-08-05 12:47 UTC by dardiv

Add sensors for text recognition.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-25 18:46 UTC, ndrnour requested changes
remotely reviewed over a slack call, please adopt your code as discussed

2020-08-25 19:08 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/TextDetectionResourceTest.kt
> +
a grant permission rule for the camera is missing in this test and in  `FaceDetectionResourceTest.java`, 
please add the following rule to both files.
`@get:Rule
    var runtimePermissionRule: GrantPermissionRule =
        GrantPermissionRule.grant(Manifest.permission.CAMERA)`

2020-08-25 21:33 UTC, ndrnour commented
one last thing, please increase the  `CURRENT_CATROBAT_LANGUAGE_VERSION` in `Constants.java`

2020-08-26 17:49 UTC, ndrnour approved these changes
LGTM

2020-09-07 09:36 UTC, merged

2020-09-07 09:37 UTC, wslany commented
Thanks!