CATROID-671 refactor SpeakAction to Kotlin
Catrobat/Catroid pull request #3738
Opened 2020-08-10 15:00 UTC by hofcle78

SpeakAction is refactored to Kotlin
[TextToSpeech.OnUtteranceCompletedListener](https://developer.android.com/reference/kotlin/android/speech/tts/TextToSpeech.OnUtteranceCompletedListener?authuser=0&hl=pl) is deprecated in Kotlin.
It is replaced with [UtteranceProgressListener](https://developer.android.com/reference/kotlin/android/speech/tts/UtteranceProgressListener?authuser=0&hl=pl).

https://jira.catrob.at/browse/CATROID-671

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-02 10:20 UTC, hofcle78 commented
`TextToSpeechHolder.java`, `UtteranceProgressListenerContainer.java` and `UtteranceProgressListenerContainerTest.java` is now refactored to Kotlin!

2020-09-26 11:16 UTC, christophsiegl requested changes
Added some suggestions. The use of Elvis operators makes such if statements much easier.
Please verify that all CI checks have passed.

2020-09-26 11:16 UTC, christophsiegl commented on catroid/src/main/java/org/catrobat/catroid/stage/TextToSpeechHolder.kt
> +        var text = text
Using an Elvis operator would be nice. If statement below would be obsolete

2020-09-30 11:22 UTC, hofcle78 commented
> Added some suggestions.

Done.
The same CI checks failed like in [CATROID-668](https://jenkins.catrob.at/job/Catroid/job/PR-3724/39/#showFailuresLink)

2020-10-07 12:21 UTC, christophsiegl approved these changes
Nice, looks good!
Don't know why CI checks are failing. Seems like a Jenkins issue or a genereal issue in the develop branch.

2020-10-08 15:52 UTC, gPathpp requested changes
First of all: great work! You have done well! 👍 
But some little things:
1. Please do not use "!!" since it can cause an NPE
2. Please refactor the code such that it is as readable as possible
3. Try to get rid of the nullable types.

Please read this pages:
https://kotlinlang.org/docs/reference/null-safety.html#null-safety
https://kotlinlang.org/docs/reference/properties.html#properties-and-fields
https://kotlinlang.org/docs/reference/object-declarations.html#object-declarations

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/TextToSpeechHolder.kt
> +        if (textToSpeech != null) {
Please remove this if.
Have a look at https://kotlinlang.org/docs/reference/null-safety.html#safe-calls

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/TextToSpeechHolder.kt
> +        if (utteranceProgressListenerContainer!!.addUtteranceProgressListener(speechFile,
Never use "!!" it's an "assert not null". if the value is null => Process crash. 
Do we really want a NPE here?
Have a look at https://kotlinlang.org/docs/reference/null-safety.html#the--operator

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/TextToSpeechHolder.kt
> +        var instance: TextToSpeechHolder? = null
Please use "val" instead
val instance = TextToSpeechHolder() 
(much less code and not a nullable type)

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/UtteranceProgressListenerContainer.kt
> +    override fun onStart(utteranceId: String) {
Are these Log methods necessary?

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/UtteranceProgressListenerContainer.kt
> +        Log.d(javaClass.simpleName, "onStart()")
This does probably not belong here, does it?

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/UtteranceProgressListenerContainer.kt
> +        for (listener in listeners[utteranceId]!!) {
No "!!" please.

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAction.kt
> +            if (text == null) "" else text?.interpretString(sprite)
Please use "?:" instead.
https://kotlinlang.org/docs/reference/null-safety.html#elvis-operator

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAction.kt
> +        listener = object : UtteranceProgressListener() {
Please refactor this.

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/content/actions/SpeakAction.kt
> +    fun setSprite(sprite: Sprite?) {
Is this setter really useful?
Please make sprite public.
In Kotlin Getter and setter are automatically generated.
https://kotlinlang.org/docs/reference/properties.html#properties-and-fields

2020-10-08 15:52 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/TextToSpeechHolder.kt
> +        var instance: TextToSpeechHolder? = null
Since this is a Singelton you can use "object" as well.

https://kotlinlang.org/docs/reference/object-declarations.html#object-declarations

2020-11-11 16:45 UTC, gPathpp approved these changes

2020-11-24 16:58 UTC, merged