CATROID-677 Make "No internet" message easier to read
Catrobat/Catroid pull request #3739
Opened 2020-08-10 16:06 UTC by blindguardian50

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-16 02:21 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
> +			} else {
actually the old way by showing the toast was completely wrong, cause the error roast will be shown even if the error isn't a network error. for more info please have a look at errors that this callback handle. [webViewErrors](https://developer.android.com/reference/kotlin/android/webkit/WebViewClient#constants)

to indicate no internet access, just compare `errorCode`  or `description` with the corresponding values, which means no need to check if the device has internet access in the first place.

2020-08-16 02:30 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
>  			}
in short, please change the body of this callback to suggested :
```suggestion
			if (errorCode == ERROR_HOST_LOOKUP || description.contains("ERR_INTERNET_DISCONNECTED")) {
				setContentView(R.layout.activity_network_error);
				setSupportActionBar(findViewById(R.id.toolbar));
				getSupportActionBar().setIcon(R.drawable.pc_toolbar_icon);
				getSupportActionBar().setTitle(R.string.app_name);
			} else {
				Log.e(TAG, "could'nt connect to the server! info: " + description + " : " + errorCode);
			}
```

2020-08-16 02:32 UTC, ndrnour commented on catroid/src/main/res/layout/activity_network_error.xml
> +        android:layout_height="match_parent"
please change to 
```suggestion
        android:layout_height="wrap_content"
```

2020-08-26 15:03 UTC, ndrnour approved these changes

2020-09-10 17:43 UTC, wslany requested changes
Without internet, when the users taps on "Catrobat community" on the main menu, the following screen (which is too dark) still appears:
![image](https://user-images.githubusercontent.com/1747888/92774207-88dfba00-f39d-11ea-9a07-cff71444c393.png)
Same also for media gallery.

Tested with build https://jenkins.catrob.at/job/Catroid/job/PR-3739/16/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-3739-16.apk on a Galaxy S20 Ultra with Android 10.

2020-09-14 14:51 UTC, blindguardian50 commented
This is very strange as i tested https://jenkins.catrob.at/job/Catroid/job/PR-3739/20/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-3739-20.apk because https://jenkins.catrob.at/job/Catroid/job/PR-3739/16/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-3739-16.apk is not available anymore.  When I tested it with the emulator in Android Studio with Android 10 everything seemed to work when the user taps on "Catrobat community" and when the media gallery should be opened too. Do you get the above error message also with other devices or other android versions? Because since I cannot reproduce the error I don't know how to correct it. The intended screen that I always get looks like this:
![grafik](https://user-images.githubusercontent.com/43927004/93099864-ce0b3100-f6a8-11ea-8daf-7919f1687a58.png)
but I never get the screen you showed above

2020-10-23 16:06 UTC, gPathpp approved these changes
LGTM!
Please rebase 🙏

2020-10-24 05:00 UTC, wslany requested changes
I just tried the following, using browser stack with a Samsung Galaxy S20 Ultra, Android 10, with a simulated unavailable network, and with https://jenkins.catrob.at/job/Catroid/job/PR-3739/36/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-3739-36.apk as the build. 

When I tried to add a new object using the media gallery, the following screen is shown:
![image](https://user-images.githubusercontent.com/1747888/97068110-da967980-15c4-11eb-86a3-87bd1dea9f32.png)
Trying the leave this screen using the Android back button leads to an ANR and a timeout. 

Same behavior when I tap on the "Catrobat community" on the main screen.

When following the same steps on a Samsung Galaxy S6 with Android 5.0, the same screen is again shown:
![image](https://user-images.githubusercontent.com/1747888/97068219-02d2a800-15c6-11eb-8ba3-f24fccb76482.png)

I also tried it on a Pixel 4 with Android 11, with the same result:
![image](https://user-images.githubusercontent.com/1747888/97068234-3f060880-15c6-11eb-9a1e-8596979dbb23.png)

I cannot imagine what's wrong. Have you tried with real devices? Thanks.

2020-10-27 09:12 UTC, gPathpp commented
> I cannot imagine what's wrong. Have you tried with real devices? Thanks.

Yes, I've tested it with my Android 10 Device (One Plus 6) and multiple Emulators, it works perfectly fine.
It's strange that it doesn't work with those devices. Is it possible for @blindguardian50 to debug on these phones via browser?

2021-05-21 20:07 UTC, closed without merging