CATROID-691: user language sensor for locale
Catrobat/Catroid pull request #3752
Opened 2020-08-18 03:14 UTC by ndrnour

* add new languageTags to list of languages {"af", "bn", "fi", "ha", "ig", "kk", "si", "sr", "tw"}
* refactor language setting

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-23 17:33 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java
> +			"si", "th", "zh-CN", "zh-TW", "ja", "ko"};
'in' replaced by 'id' [Bahasa Indonesia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#ID)
'iw' replaced by 'he' [עברית (Hebrew)](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#HE)

2020-08-24 06:11 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/common/SharedPreferenceKeys.java
> +			"si", "th", "zh-CN", "zh-TW", "ja", "ko"};
Thank you for clearing that up!

2020-08-24 06:11 UTC, juliajulie95 approved these changes

2020-08-24 13:47 UTC, wslany requested changes
Thanks! A few issues:

- Changing the language via the Catroid settings dialog is only reflected in a change in the sensor value _after_ the app has been force closed. A simple exit via back button from the app and "restart" is insufficient. Please correct this so that a change in the user interface language will be immediately reflected in the sensor's value when the project is executed the next time. I.e., no force closing should be necessary. Please add a test case for this.
- In the specification of the ticket, it was written that the response shall be as in https://jira.catrob.at/browse/CATROID-682 where it was defined as the language locale code, e.g., de_AT for Austrian German. However, currently the reported value of the string is "Deutsch (Österreich)" instead. Please correct this. The current way (full language name in the local language) makes it difficult for a project to handle these values since they depend on the set language. 
- The Catrobat language version number needs to be increased since a new sensor function has become available with this ticket.

2020-08-25 04:22 UTC, ndrnour commented
> Thanks! A few issues:
> 
> * Changing the language via the Catroid settings dialog is only reflected in a change in the sensor value _after_ the app has been force closed. A simple exit via back button from the app and "restart" is insufficient. Please correct this so that a change in the user interface language will be immediately reflected in the sensor's value when the project is executed the next time. I.e., no force closing should be necessary. Please add a test case for this.
> * In the specification of the ticket, it was written that the response shall be as in https://jira.catrob.at/browse/CATROID-682 where it was defined as the language locale code, e.g., de_AT for Austrian German. However, currently the reported value of the string is "Deutsch (Österreich)" instead. Please correct this. The current way (full language name in the local language) makes it difficult for a project to handle these values since they depend on the set language.
> * The Catrobat language version number needs to be increased since a new sensor function has become available with this ticket.

fixed

2020-08-25 13:00 UTC, wslany approved these changes

2020-08-25 13:00 UTC, wslany commented
Thanks!

2020-08-25 13:01 UTC, merged