CATROID-522 References to a local UserVariable within a Scene will be changed in all Scenes
Catrobat/Catroid pull request #3754
Opened 2020-08-18 18:05 UTC by Rawbat

The bug was caused because all user variables and lists were handled equally as global variables. By adding a check in the update user data references function if the variable or list is global or not this bug can be avoided.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-03 12:07 UTC, mstoeg requested changes
Very nice fix, but please have a look at my remarks!

2020-09-03 12:07 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/content/Scene.java
> +				|| currentProject.getMultiplayerVariables().contains(item)) {
Maybe you could make this condition more readable if you outsource it to a function, e.g. *isGlobalVariable(UserData<?> item)*

2020-09-03 12:07 UTC, mstoeg commented on catroid/src/test/java/org/catrobat/catroid/test/content/bricks/UpdateVariableInFormulaBrickTest.java
> +		ProjectManager.getInstance().getCurrentProject().addUserVariable(userVariable);
Is it really necessary to add the userVariable in each testcase? I would prefer to add it in the setUp() method by simply calling project.addUserList(userList) and project.addUserVariable(userVariable) once. Same applies for all the other Tests.

2020-09-03 15:46 UTC, mstoeg requested changes

2020-09-03 15:46 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/utils/Utils.java
> +			return true;
Please just return the condition here: *return currentProject.getUserVariables().contains(item) || ...*
And I would not place this method in the Utils class but rather in the Project class as an instance method.

2020-09-03 18:27 UTC, mstoeg approved these changes
Well done!

2020-09-10 17:05 UTC, merged

2020-09-10 17:05 UTC, wslany commented
Thanks!!