CATROID-15 refactor Touches Color
Catrobat/Catroid pull request #3758
Opened 2020-08-19 15:04 UTC by gPathpp

refactor TouchesColor
add simple ColorTouchesColor

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-20 13:42 UTC, adnaribo commented on catroid/src/main/java/org/catrobat/catroid/common/Constants.java
> +	public static final float CURRENT_CATROBAT_LANGUAGE_VERSION = 1f;
@wslany please decide if we can move to 1

2020-08-20 13:43 UTC, adnaribo approved these changes
looks good to me :)

2020-08-25 11:55 UTC, wslany requested changes
Thanks!!

As discussed via slack (for others: there were cases where it didn't report the correct value --- was easier to show than explain here).

2020-09-17 04:42 UTC, wslany approved these changes

2020-09-17 04:42 UTC, merged

2020-09-17 04:42 UTC, wslany commented
Thanks!!!