CATROID-696 Fix behavior of visual placement dialog
Catrobat/Catroid pull request #3762
Opened 2020-08-24 08:33 UTC by mstoeg

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-26 12:24 UTC, ndrnour requested changes

2020-08-26 12:24 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
> -
looks good, please just revert this

2020-08-26 17:33 UTC, ndrnour approved these changes

2020-09-10 17:34 UTC, merged

2020-09-10 17:34 UTC, wslany commented
Thanks!