GSOC-DS-005 Refactor project loading
Catrobat/Catroid pull request #3764
Opened 2020-08-24 16:33 UTC by DinosaurierRex

- Moved all project loading specific tasks to new class
- Tried to avoid using context that much (Interface and implementation of a Stringprovider for Project loading)
- Refactor of test and code usages

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-25 09:03 UTC, gPathpp requested changes

2020-08-26 10:01 UTC, DinosaurierRex commented
@gPathpp Requested changes resolved. Tests which fail on Jenkins run locally without Problems. May this is still related to slow emulators for test runs.

2020-08-26 10:43 UTC, gPathpp requested changes
Looks good!

2020-08-26 10:43 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/io/ProjectLoadAndUpdate.kt
> +        for (scene in project.sceneList) {
Please use Project Updater

2020-08-26 10:43 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/io/ProjectLoadAndUpdate.kt
> +                    if (objectData is LookData) objectData.file = duplicateFile(objectData.file)
As discussed, please use callbacks instead

2020-08-26 15:07 UTC, gPathpp approved these changes
Well done 👍

2021-06-10 14:28 UTC, closed without merging