CATROID-625 Timer / Reset timer brick
Catrobat/Catroid pull request #3768
Opened 2020-08-28 11:03 UTC by Rawbat

https://jira.catrob.at/browse/CATROID-625

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-08-31 14:25 UTC, blindguardian50 approved these changes
Looks good to me!

2020-09-12 14:17 UTC, wslany requested changes
Please change the text on the brick as indicated in the inline suggestion. 

Also, I just tried to import https://github.com/Catrobat/Catroid/raw/14c3887fba8e304bce93b33ad8b305367dba3ae0/catroid/src/androidTest/assets/catrobatTests/bricks/device/ResetTimer/testResetTimer.catrobat using https://jenkins.catrob.at/job/Catroid/job/PR-3768/lastSuccessfulBuild/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-3768-6.apk but there was an error and the project file could not be loaded.

2020-09-12 14:17 UTC, wslany commented on catroid/src/main/res/values/strings.xml
> +    <string name="brick_reset_timer">Reset Timer</string>
```suggestion
    <string name="brick_reset_timer">Reset timer</string>
```
All our bricks use normal English capitalization rules. Also, see the jira ticket.

2020-10-15 13:51 UTC, christophsiegl approved these changes
Looks good!

2020-10-22 06:05 UTC, wslany approved these changes

2020-10-22 06:06 UTC, merged

2020-10-22 06:06 UTC, wslany commented
Thanks!