CATROID-197 Pause X beats
Catrobat/Catroid pull request #3769
Opened 2020-08-31 13:09 UTC by Rawbat

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-01 08:37 UTC, adnaribo requested changes
Please add some tests either unit tests or language tests.

2020-09-01 08:37 UTC, adnaribo commented on catroid/src/main/java/org/catrobat/catroid/content/actions/PauseForBeatsAction.java
> +			int pausedBeats = beats == null ? Integer.valueOf(0) : beats.interpretInteger(sprite);
Please use here an if else condition for better readability

2020-09-01 17:34 UTC, adnaribo approved these changes
Looks good :+1:

2020-09-08 18:25 UTC, adnaribo approved these changes

2020-09-08 18:39 UTC, adnaribo approved these changes

2020-09-18 09:15 UTC, wslany commented on catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java
> +				"https://wiki.catrobat.org/bin/view/Documentation/Brick%20Documentation/PauseForBeatsBrick");
```suggestion
				"https://wiki.catrobat.org/bin/view/Documentation/BrickDocumentation/PauseForBeatsBrick");
```
Sorry, changed since yesterday.

2020-09-18 09:56 UTC, merged

2020-09-18 09:56 UTC, wslany commented
Thanks!