CATROID-375 Fix bug with invisible objects
Catrobat/Catroid pull request #3770
Opened 2020-09-02 09:14 UTC by mstoeg

- Refactor SingleSprite as it is actually not necessary to distinguish between Sprite and SingleSprite

https://jira.catrob.at/browse/CATROID-375

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-15 14:32 UTC, dandrawes requested changes
Good job!

2020-09-15 14:32 UTC, dandrawes commented on catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
> +			//convertedSprite = new SingleSprite(name);
Please remove this comment.

2020-09-16 05:04 UTC, dandrawes approved these changes

2020-09-17 05:12 UTC, wslany commented
Thanks!!

2020-09-17 05:12 UTC, merged