CATROID-706 Add catrobat language test for sine function
Catrobat/Catroid pull request #3772
Opened 2020-09-03 21:10 UTC by dandrawes

Catrobat language test for sine function
https://jira.catrob.at/browse/CATROID-706

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [X] Include the name of the Jira ticket in the PR’s title
- [X] Include a summary of the changes plus the relevant context
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [X] Include reasonable and readable tests verifying the added or changed behavior
- [X] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Stick to the project’s gitflow workflow
- [X] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-23 13:54 UTC, Kropiunig approved these changes

2020-10-11 07:24 UTC, wslany requested changes
Thanks. Please delete the testcase sin(45+45) since there's already one for sine(90). 

Also, for the sin(45) test, I added an explicit limitation of the mathematical precision, as it was not mathematically correct as it was, but dependent on implementation details. As such, it needs to be made correct to allow this to be a specification for future implementations or on different hardware architectures. 
![image](https://user-images.githubusercontent.com/1747888/95672684-492a0f00-0ba3-11eb-9781-3c8ba4be25a9.png)

I left it as it was with sine(60) and sine(-60) since there it was formulated in a mathematically correct way, even though it might lead to failures on future devices depending on their implementation of the Catrobat language --- in  that case the test may have to be adapted also for that future implementations to make the comparison work fine again. For now it is fine however. 

Please replace with the attached test.
[testSineFunction.zip](https://github.com/Catrobat/Catroid/files/5360717/testSineFunction.zip)

2020-11-02 22:58 UTC, Koell approved these changes
Requested changes were made

2020-11-04 16:37 UTC, wslany approved these changes

2020-11-04 16:39 UTC, merged

2020-11-04 16:39 UTC, wslany commented
Thanks!