CATROID-725 Added context sensitive regular expression editor dialog
Catrobat/Catroid pull request #3778
Opened 2020-09-08 09:24 UTC by k01bi

CATROID-725 Added context sensitive regular expression editor dialog. If first param of a regular expression is selected, an extended dialog option is shown. The dialog shown has the title "Change regular expression" and has a "Assistant" button without implemented functionality.
https://jira.catrob.at/browse/CATROID-725

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-08 13:51 UTC, UneclStivun approved these changes
looks good to me

2020-09-08 14:54 UTC, wslany requested changes
Nice! However, the Assistant option incorrectly does not appear when the (complete) first parameter is in focus but does _not_ contain a string, yet the user tapped on the Abc button. Since the intent of the user here is most likely to replace the current formula by a string (that's why the user pressed on Abc at that moment), the assistant should be offered: 
![image](https://user-images.githubusercontent.com/1747888/92492491-aec95b00-f1f3-11ea-93eb-4132c5eb3457.png)

Note that in case the first parameter of the join would have been selected instead of the whole join formula element, then tapping on Abc should not show the Assistant button.

2020-09-10 08:52 UTC, artjom404 approved these changes
Looks good to me.

2020-09-10 10:34 UTC, wslany approved these changes

2020-09-10 10:38 UTC, merged

2020-09-10 10:38 UTC, wslany commented
Thanks!