Catroid-752 - Feature flag as condition for RegEx assistant functionalities
Catrobat/Catroid pull request #3795
Opened 2020-09-14 12:20 UTC by UneclStivun

-add feature flag in build.gradle
-add condition for RegEx assistant functionalities via feature flag

https://jira.catrob.at/browse/CATROID-752

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-14 12:32 UTC, david-loe approved these changes
looks fine to me.

2020-09-14 14:15 UTC, wslany commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/dialog/RegularExpressionAssistantDialogTest.java
> +			//Click Catrobat RegEx Wiki Button
```suggestion
```
Code is clear enough.

2020-09-14 14:21 UTC, wslany requested changes

2020-09-14 14:21 UTC, wslany commented on catroid/src/main/res/values/strings.xml
> +    <string name="formula_editor_dialog_wiki_button">Catrobat RegEx Wiki</string>
```suggestion
    <string name="formula_editor_dialog_wiki_button">More information</string>
```

2020-09-15 08:32 UTC, M0d0s approved these changes

2020-09-17 12:29 UTC, wslany approved these changes

2020-09-17 12:33 UTC, merged

2020-09-17 12:34 UTC, wslany commented
Thanks!