CATROID-196 Change tempo by X
Catrobat/Catroid pull request #3806
Opened 2020-09-17 13:15 UTC by hofcle78

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-22 10:55 UTC, Rawbat requested changes
Nice!

Can you add a language test to check the functionality of this brick? Also please increase the catrobat language version.

2020-09-22 10:55 UTC, Rawbat commented on catroid/src/main/java/org/catrobat/catroid/content/actions/ChangeTempoByAction.java
> +			int newTempo = tempo == null ? Integer.valueOf(0) : tempo.interpretInteger(sprite);
Change this to an if-else statement for better readability please

2020-09-22 10:55 UTC, Rawbat commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/ChangeTempoBrick.java
> +		addAllowedBrickField(BrickField.TEMPO, R.id.brick_change_tempo_edit_text);
Please intruduce a new entry in the BrickField called TEMPO_CHANGE and use it in this brick instead of TEMPO

2020-10-20 11:13 UTC, Rawbat approved these changes
Looks good, thanks!

2020-10-23 05:07 UTC, wslany commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java
> +		soundBrickList.add(new ChangeTempoByNBrick(0));
```suggestion
		soundBrickList.add(new ChangeTempoByNBrick(10));
```

2020-10-24 03:30 UTC, merged

2020-10-24 03:31 UTC, wslany commented
Thanks!