Catroid-735 Fix vertical distortion of camera image on Android 5 and 6 devices
Catrobat/Catroid pull request #3813
Opened 2020-09-19 19:37 UTC by mandelbrot2357

Implements scaling of camera image for older Android versions

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-23 12:47 UTC, blindguardian50 approved these changes

2020-10-09 10:06 UTC, wslany requested changes
There's no distortion anymore, but now the face localization on the rear camera does not work (tested with Android 5 on a Note 3, and Android 9 on Note 8).

2020-10-09 15:16 UTC, wslany commented
> There's no distortion anymore, but now the face localization on the rear camera does not work (tested with Android 5 on a Note 3, and Android 9 on Note 8).

@mandelbrot2357 thanks for finding out that the face localization failure is not due to this PR but seems to have been newly introduced with https://github.com/Catrobat/Catroid/pull/3734 --- another very good reason to add automatic real device tests using our robot arms for everything related to the camera.

2020-10-09 15:16 UTC, wslany approved these changes

2020-10-09 15:16 UTC, merged