CATROID-623 "if( condition , then , else )" Function
Catrobat/Catroid pull request #3824
Opened 2020-10-02 03:37 UTC by Rawbat

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-10-13 13:33 UTC, christophsiegl commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
> +		for (int index = 0; index < additionalChildren.size(); index++) {
why not using a for loop like in L252? Wouldn't it be less clumsy?

2020-10-13 13:41 UTC, christophsiegl commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaElement.java
> +
L321 in updateCollisionFormulaToVersion: Not sure if this also has to be done for our additional children?

2020-10-13 14:17 UTC, christophsiegl commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/InternFormulaKeyboardAdapter.java
> +		returnList.add(new InternToken(InternTokenType.FUNCTION_NAME, function.name()));
InterTokenType.x is already imported. Please use "FUNCTION_NAME" without "InternTokeType." like in buildDoubleParameterFunction(). Also apply this change to each used InternTokeType in buildTripleParameterFunction().

2020-10-14 07:46 UTC, christophsiegl requested changes
Functionality looks good!
Added some little suggestions.
Please extend the language test with a 'NaN' case (as stated in the ticket description) to verify this functionality.
Please add a short summary about your changes to the commit message.

2020-10-15 07:51 UTC, christophsiegl approved these changes
Great!

2020-10-23 04:51 UTC, wslany requested changes
Great, but please change the first default parameter to the boolean value "false" (not a string; false can be found under the "Logic" button) instead of 1.

In the Catrobat Language Test testIfThenElseFunction.catrobat, please do not use intermediate variables. Instead, write the formulas directly into the Assert bricks.
![image](https://user-images.githubusercontent.com/1747888/96957816-00a41700-14fc-11eb-91bf-3b001a3aa33f.png)

If you only change the testIfThenElseFunction.catrobat project instead of writing it afresh, please do not forget to delete the variables:
![image](https://user-images.githubusercontent.com/1747888/96957746-ca669780-14fb-11eb-9d54-98d35bf340aa.png)

2020-10-23 05:04 UTC, wslany commented
Also, please increase CURRENT_CATROBAT_LANGUAGE_VERSION in catroid/src/main/java/org/catrobat/catroid/common/Constants.java since the xml structure changes with this function.

2020-10-27 16:23 UTC, christophsiegl approved these changes

2020-10-27 16:26 UTC, christophsiegl requested changes
Please resolve merge conflict in Constants.java.

2020-10-28 07:02 UTC, christophsiegl approved these changes

2020-10-28 12:29 UTC, wslany approved these changes

2020-10-28 12:53 UTC, merged

2020-10-28 12:54 UTC, wslany commented
Thanks!