CATROID-516 Remove redundant if statement
Catrobat/Catroid pull request #3827
Opened 2020-10-05 13:33 UTC by adnaribo

Removing redundant if statements. https://jira.catrob.at/browse/CATROID-516

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-28 14:40 UTC, dandrawes requested changes
Please fix the two small stated issues.

2020-12-28 14:40 UTC, dandrawes commented on catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/ev3/EV3Reply.java
> +		return getStatusByte() == NO_ERROR;
This should be: `return getStatusByte() != NO_ERROR;`

2020-12-28 14:40 UTC, dandrawes commented on catroid/src/main/java/org/catrobat/catroid/devices/mindstorms/nxt/NXTReply.java
> +		return getStatusByte() == NO_ERROR;
This should be: `return getStatusByte() != NO_ERROR;`

2021-04-25 20:22 UTC, dandrawes approved these changes
Looks good now!

2021-04-26 10:54 UTC, merged

2021-04-26 10:54 UTC, wslany commented
Thanks!