CATROID-19 Enable undo of single brick deletion
Catrobat/Catroid pull request #3829
Opened 2020-10-10 06:22 UTC by mstoeg

- Copy code.xml file to undo.xml if an undo_xml option is available
- Replace code.xml with previously copied undo_xml.xml when undo is executed
- Refactor undo of brick spinner
https://jira.catrob.at/browse/CATROID-19

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-10-30 12:56 UTC, BeinhAlex commented on catroid/src/main/res/values-de/strings.xml
> -    <string name="brick_read_variable_from_file_center">Aus Datei</string>
Please delete the variables from strings-de and put them into string.xml

2020-10-30 12:59 UTC, BeinhAlex requested changes
Please move the strings into the correct file

2020-11-02 14:37 UTC, BeinhAlex approved these changes
Looks good!

2020-11-07 01:51 UTC, wslany requested changes
@mstoeg Please only make changes in the default strings.xml --- all other translation files will be overwritten when the files are imported from CrowdIn (@BeinhAlex please also take note for future code reviews). 

Martin, please remove all the _non_ US English (default language) translation xml files. Once the PR is merged, please add the non-English translations via https://translate.catrobat.org/

2020-11-07 02:01 UTC, wslany commented
@mstoeg one more issue: https://jira.catrob.at/browse/CATROID-19 specifies
> This undo opportunity should exist only directly after deleting the brick. As soon as the user does anything besides scrolling up and down in the script view, e.g., when the user deletes another brick in the same way, or the user edits a parameter field etc, this undo opportunity for the deletion of the (first) brick is lost, and thus the undo cannot be applied anymore to any earlier deletion or other action.

However, when one deletes a brick in the current state of the PR and then moves other bricks, the undo arrow is still there. Tapping on undo moves the bricks back to their respective original positions and then reinserts the deleted brick. This should not be possible. Correct behavior should be that as soon as another brick has been moved, the undo button shall not be available anymore.

2020-11-08 07:41 UTC, mstoeg commented
@wslany Thank you for the information! I am aware that changes to the contents of a string resource or adding new string resources should only be done in the default strings.xml. However, in this case I wasn't quite sure how to handle the deletion of whole entries (not just the content) because otherwise lint would complain that there are strings in other language files but not in the default strings.xml.

2020-12-17 09:37 UTC, BeinhAlex approved these changes
Well done!

2020-12-18 15:14 UTC, wslany approved these changes

2020-12-18 15:59 UTC, merged

2020-12-18 15:59 UTC, wslany commented
Thanks!!