CATROID-734 Update Design for Terms of Use and Service
Catrobat/Catroid pull request #3851
Opened 2020-10-29 10:42 UTC by dandrawes

https://jira.catrob.at/browse/CATROID-734
New design for Terms of Use and Service pop-up

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-10-29 20:06 UTC, mstoeg requested changes
Looks good! Just have a look at my coding style advice.

2020-10-29 20:06 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
> +			View view = View.inflate(this, R.layout.privacy_policy_view, null);
Please outsource this to an extra method (e.g. showTermsOfUseDialog()) in order to keep the onCreate() method compact.

2020-10-29 20:06 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.java
> +					.setNegativeButton(R.string.decline, new DialogInterface.OnClickListener() {
Please use lambda-expressions here. They should be suggested by Android Studio automatically.

2020-10-31 07:14 UTC, mstoeg approved these changes
Well done!

2020-11-05 02:17 UTC, wslany requested changes
Thank you, very nice. 

However, when one declines the "Terms of Use and Service" dialog, the following screen appears:
![image](https://user-images.githubusercontent.com/1747888/98186462-10b1f280-1f0f-11eb-8af4-1e4a2cb9c440.png)
Please change the text and name in https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/res/values/strings.xml#L322 from
```
    <string name="declined_privacy_agreement_alert">To use our app, it is necessary to accept our Privacy Policy.
```
to:
```
    <string name="declined_terms_of_use_and_service_alert">To use our app, it is necessary to accept our Terms of Use and Service.
```
This also has implications for https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/res/layout/declined_privacy_agreement_alert_view.xml , both in used resources as well as the name of that file, since it does not refer to the privacy policy anymore but instead now to the terms of use and service.

Note that the share.catrob.at link on this second screen does not work. Instead, tapping on the link shall open the community site in the user's preferred browser (_not_ in a webview), much like in the following dialog:
![image](https://user-images.githubusercontent.com/1747888/98188125-bca90d00-1f12-11eb-9db1-5ecf8b6467bd.png)
Please use the BASE_APP_URL_HTTPS constant from https://github.com/Catrobat/Catroid/blob/5ae47a16b7089a9bcc878f3e82aded57dcd93e60/catroid/src/main/java/org/catrobat/catroid/common/Constants.java#L117 for this link. This ensures that the correct flavor of share is opened here.

Also, when the user then taps OK on that second screen, he or she is shown an empty black screen on which there is no button nor text (tapping on the Android back button apparently exits Catroid). Instead, tapping on OK shall return to the first dialog (which you have correctly implemented).

2020-11-21 08:32 UTC, mstoeg requested changes
Looks good now, as far as the remarks from @wslany are concerned. However, there is still an odd behavior if the back button is pressed on the first welcome-dialog. I think instead of showing a black screen it would be better to just finish the activity there.

2020-11-22 10:48 UTC, mstoeg approved these changes

2020-11-22 12:24 UTC, wslany approved these changes

2020-11-22 12:25 UTC, merged

2020-11-22 12:25 UTC, wslany commented
Thanks!