CATROID-758 Copy look brick
Catrobat/Catroid pull request #3852
Opened 2020-10-30 00:06 UTC by blindguardian50

The brick copies the current look and inserts it in the looklist.

https://jira.catrob.at/browse/CATROID-758

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-10-31 22:10 UTC, dandrawes approved these changes
Well done!

2020-11-06 12:33 UTC, wslany requested changes
Thanks!!

How complex is it that looks imported with a "Get image from 'https://catrob.at/penguin' and use as current look" can also be copied (and then become a real, normal look) with the new brick? This would be very useful, and also would be very natural behavior. If it is very complex, we can also make a bug ticket and handle it there later. LMK.

2020-11-06 12:33 UTC, wslany commented on catroid/src/main/java/org/catrobat/catroid/common/BrickValues.java
> +	public static final String COPY_LOOK = "name of copied look";
This should be a translatable resource in strings.xml

2020-11-17 12:50 UTC, dandrawes requested changes

2020-11-17 12:50 UTC, dandrawes commented on catroid/src/main/java/org/catrobat/catroid/content/actions/LookRequestAction.kt
> +            insertInLookList(this)
If a "Get image from" brick is not used in combination with the "Copy look" brick a new look is created, which should not be the case.

2020-11-24 15:20 UTC, dandrawes approved these changes
Good job, looks good now!

2020-11-25 08:48 UTC, wslany requested changes
Thanks!! 

Please increase the Catrobat language version in https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/common/Constants.java#L42 (please do not increase to 1.0 --- this is reserved to when the user-defined brick functionality is merged, which hopefully will be very soon).

I'm keeping this ticket in PO review since this a small change and no second code-review is necessary. Please reply to this comment to let me know when I can merge it. Thanks!

2020-11-26 19:23 UTC, blindguardian50 commented
Thanks for the review, I have updated the language version, you can merge it now!

2020-11-27 00:51 UTC, wslany approved these changes

2020-11-27 02:06 UTC, merged

2020-11-27 02:06 UTC, wslany commented
Thanks!