CATROID-802 Refactor StoreCSVIntoUserListAction to Kotlin
Catrobat/Catroid pull request #3866
Opened 2020-11-09 22:40 UTC by qlin93

Refactored StoreCSVIntoUserListAction to Kotlin

https://jira.catrob.at/browse/CATROID-802

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-11-17 11:26 UTC, Koell requested changes

2020-11-17 11:26 UTC, Koell commented on catroid/src/main/java/org/catrobat/catroid/content/actions/StoreCSVIntoUserListAction.kt
> +                    }
please change in line 80&83 the userList!! to userList?
if you don't check for NPE don't enforce them, with the elvis-operator(?) kotlin ignores the function when it is NULL

2020-11-17 11:27 UTC, Koell commented on catroid/src/main/java/org/catrobat/catroid/content/actions/StoreCSVIntoUserListAction.kt
> +                    }
the rest of the conversion was fine

2020-11-19 19:24 UTC, Koell approved these changes
:+1:

2020-12-06 13:43 UTC, gPathpp requested changes
Well done!
Please, do not only rewrite the code to Kotlin but also try to improve the code quality (Clean Code).
Thanks!

2021-01-10 17:51 UTC, gPathpp requested changes

2021-01-10 17:51 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/content/actions/StoreCSVIntoUserListAction.kt
> +}
Well done!

PLEASE EXPLAIN: Does the changed behaviour affect the program? (After any Exception you return a default value and also the UserList reset is missing)
If this is not intended, I would suggest returning null and using "?: return" in the update method.

PLEASE ADD (if missing): a test for its original behaviour.

2021-01-11 15:40 UTC, qlin93 commented
@gPathpp Thanks! The changes did not affect the program. By returning default values the update method would return without making any changes to the UserList, therefore the reset was unnecessary. But since your suggestion with returning null and using "?:return" is a lot cleaner and easier to read I have changed it.  I also made the member variables public. 

Regarding the test, there are five existing Catrobat language tests that test the intended behaviour of the program.

2021-01-17 12:38 UTC, gPathpp approved these changes
LGTM!

2021-01-18 20:42 UTC, merged

2021-01-18 20:42 UTC, wslany commented
Thanks!