Catroid 816
Catrobat/Catroid pull request #3871
Opened 2020-11-14 21:37 UTC by bprattes

Add basic Catblocks 2D functionality to Catroid.
https://jira.catrob.at/browse/CATROID-816

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-11-14 21:40 UTC, MichaelFlucher approved these changes
LGTM

2020-11-20 13:57 UTC, wslany requested changes
Awesome!

Please add a build config flag that enables the 2D view for now only in the develop version, since there are quite a number of issues. This shall be done as for instance shown here for the future multiplayer extension: https://github.com/Catrobat/Catroid/blob/13c5299201e84a08eb6fb6f503910b2c8f48e4e2/catroid/build.gradle#L166

Reason: We could not yet release the current version, since it allows to change the scripts in the 2D view (by moving parts around), which in principle is great, but these changes are currently still not kept in this version as soon as you switch back to the 1D view, so I guess the changes are just made in the Catblocks part, right? With the build config flag, we can merge Catblocks into develop but it is ignored for a release version (additional conditional code needs to be added of course for the flag). 

Also, by scrolling up you can currently switch the 2D script view to see the scripts of another object, but then tapping on the looks tab switches to the looks of the original object, thus not corresponding to the scripts. This is OK for now, but we need to fix it before we can release it, so OK to merge, but that's why we need the build config flag. 

![image](https://user-images.githubusercontent.com/1747888/99807697-2abf1800-2b40-11eb-8986-47c406669b7a.png)

Also, please fix the static analysis warnings: https://jenkins.catrob.at/job/Catroid/job/PR-3871/2/analysis/

2020-11-25 10:30 UTC, wslany approved these changes

2020-11-25 11:02 UTC, wslany requested changes
Please increase the Catrobat language version in https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/common/Constants.java#L42 (please do not increase to 1.0 --- this is reserved to when the user-defined brick functionality is merged, which hopefully will be very soon).

2020-11-26 15:15 UTC, juliajulie95 requested changes

2020-11-26 15:15 UTC, juliajulie95 commented on catroid/build.gradle
> +            buildConfigField "boolean", "FEATURE_CATBLOCKS_DEBUGABLE", "false"
Delete this if already set by default config

2020-11-26 15:15 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
> +		menu.findItem(R.id.catblocks_reorder_scripts).setVisible(false);
Hide action mode in looks and sounds

2020-11-26 15:15 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt
> +            val fragmentTransaction = fragmentManager?.beginTransaction()
deprecated, use getParentFragmentManager() if possible

2020-11-26 15:15 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt
> +    private fun initWebView(catblocksWebview: WebView) {
Naming

2020-11-26 15:15 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt
> +            @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
Do we need this? Else disable catblocks for lower android versions

2020-11-27 16:33 UTC, juliajulie95 requested changes
Please delete unused imports.
Everything else looks fine

2020-11-28 09:04 UTC, juliajulie95 approved these changes

2020-11-28 11:07 UTC, wslany approved these changes

2020-11-28 11:07 UTC, merged

2020-11-28 11:07 UTC, wslany commented
Thanks!! Awesome!