CATROID-5 Incorrect calculations with decimals
Catrobat/Catroid pull request #3876
Opened 2020-11-20 22:20 UTC by Rawbat

Fixed the bug by using BigDecimal for mathematical operations in the formula editor

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-06 19:53 UTC, adnaribo requested changes
please add some tests to verify the changed behaviour :+1:

2020-12-08 20:38 UTC, adnaribo approved these changes
Looks good, thank you :+1:

2020-12-09 21:56 UTC, wslany requested changes
Thanks, awesome that this works and was so simple!!!! 

I commited a few changes to the testcases so that they now _all_ should have failed before this fix.

However, since I am not sure what the precision of assertEquals is for doubles in this implementation (and according to http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(double,%20double) this method is actually depreciated) and how this will be guaranteed in future implementations of assertEquals, please add a Catrobat language test for it. I have already prepared one, and all asserts in it fail before your PR, and succeed with your PR: https://share.catrob.at/app/project/5bfc1783-3a67-11eb-a92d-005056a36f47 -- please rename the downloaded file to testFloatingPointArithmetic.catrobat and add it to catroid/src/androidTest/assets/catrobatTests/formula

2020-12-11 01:54 UTC, wslany approved these changes

2020-12-11 01:56 UTC, merged