CATROID-805 Pen down and stamp ignored for clones
Catrobat/Catroid pull request #3877
Opened 2020-11-21 01:16 UTC by Rawbat

Cloned sprites are not added to the currently playing scene which was used for getting the sprites and then drawing.
Fixed the bug by using the sprites of the sprite list contained in the stage listener(Which also performs the cloning process)

https://jira.catrob.at/browse/CATROID-805

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-04-10 13:37 UTC, wslany commented
Please set the target to the new release-v1.0.1 branch.

2021-05-16 11:56 UTC, adnaribo approved these changes
Looks good, please just rebase with the upstream develop :+1:

2021-05-30 17:29 UTC, wslany requested changes
Awesome, but as discussed on Slack, please add that when the object to be cloned has the pen down, its clone should also already have its pen down when it is created.

2021-05-31 08:52 UTC, adnaribo approved these changes

2021-05-31 14:17 UTC, wslany approved these changes

2021-05-31 14:18 UTC, merged

2021-05-31 14:18 UTC, wslany commented
Thanks!