CATROID-552 "color at x y( x , y )" sensor [UI only]
Catrobat/Catroid pull request #3887
Opened 2020-11-29 13:22 UTC by petbuer

Introduce a new sensor function color at x y( x , y ). This ticket includes UI changes only.

Jira: https://jira.catrob.at/browse/CATROID-552

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [X] Include the name of the Jira ticket in the PR’s title
- [X] Include a summary of the changes plus the relevant context
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Stick to the project’s gitflow workflow
- [X] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-11-30 19:52 UTC, gPathpp requested changes
As discussed today, here are my suggestions (solution for the flaws within the function) for this PR: https://github.com/petbuer/Catroid/pull/1

Please consider merging these suggestions.
(Afterward, tailor your PR to the requirements of the ticket. (Strings, etc..)) 

Nonetheless, great work!

2020-12-06 12:27 UTC, gPathpp approved these changes
Well done!
I think the language-test is not necessary, but please discuss this with @wslany.

2020-12-09 22:48 UTC, wslany reviewed
Thanks! @petbuer how far are you with CATROID-553? Because I think we should rather only merge this together with it, as we would otherwise need a new build flag just for this sensor to limit its visibility in release apks, which seems a bit excessive much to me. Also I saw that you assigned yourself already to it. PLMK.

2020-12-09 22:48 UTC, wslany commented on catroid/src/main/res/values/strings.xml
> +    <string name="formula_editor_sensor_color_at_x_y_parameter">(100,200)</string>
```suggestion
    <string name="formula_editor_sensor_color_at_x_y_parameter"  translatable="false">(100,200)</string>
```

2020-12-09 22:55 UTC, petbuer commented
OK, I will notify you when CATROID-553 is ready. I just began to work on it.

2020-12-09 23:14 UTC, wslany commented
> OK, I will notify you when CATROID-553 is ready. I just began to work on it.

Thanks. You can add it as commits to this same PR, i.e., make one PR for both tickets.

2020-12-10 20:01 UTC, merged

2020-12-10 20:01 UTC, wslany commented
Thanks!