CATROID-833 Missing tests for Catblocks integration
Catrobat/Catroid pull request #3888
Opened 2020-12-02 16:57 UTC by bprattes

Add some basic tests for Catblocks in Catroid.
https://jira.catrob.at/browse/CATROID-833

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-01-03 13:19 UTC, juliajulie95 requested changes

2021-01-03 13:19 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CatblocksScriptFragmentTest.java
> +	public void testCorrect2DObjectDispayed() {
Typo "Dispayed"

2021-01-03 13:19 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CatblocksScriptFragmentTest.java
> +		while (true) {
While loop is duplicate of test above. Do we need to check this again? Maybe delete in this test, else delete test above.

2021-01-04 09:56 UTC, juliajulie95 approved these changes

2021-01-08 16:56 UTC, wslany requested changes
Please fix the warning.

2021-01-08 16:56 UTC, wslany commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CatblocksScriptFragmentTest.java
> +				}
This results in a lint warning => 
- https://jenkins.catrob.at/job/Catroid/job/PR-3888/14/analysis/ 
- https://jenkins.catrob.at/job/Catroid/job/PR-3888/14/analysis/source.01d88343-443b-496d-90eb-a6ac09189969/#140

2021-01-11 15:45 UTC, juliajulie95 approved these changes

2021-01-18 19:59 UTC, wslany approved these changes

2021-01-18 20:01 UTC, merged

2021-01-18 20:01 UTC, wslany commented
Thanks!!