README.md
Catrobat/Catroid pull request #3889
Opened 2020-12-04 18:25 UTC by devmalik7

Hey, hope you doing good.
I have optimized this README file.I have added the links of Catrobat Home website moreover i have added help link for the beginner user who is now familiar with the contribution at CATROBAT.Hope you like it.

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-05 18:34 UTC, devmalik7 commented on README.md
> +**Catrobat** is a visual programming language and a set of creativity tools for smartphones Android apps available on Google Play and iPhone apps available on Apple's app store.
to make it clear for user.

2020-12-05 18:34 UTC, devmalik7 commented on README.md
> +* [Home Catrobat](https://catrobat.org/)
It is the link of Home page of Catrobat websites

2020-12-27 18:14 UTC, wslany requested changes
Thanks! A few changes please.

2020-12-27 18:14 UTC, wslany commented on catroid/src/main/java/org/catrobat/catroid/content/ActionFactory.java
> + * But WITHOUT ANY WARRANTY; without even the implied warranty of
Sorry, the AGP copyleft header text must remain _unchanged_, see https://www.gnu.org/licenses/gpl-howto.html

2020-12-27 18:14 UTC, wslany commented on automationScripts/createBetaTestingPocketCodeAPK.py
> +# This is done all for you:
I think (not sure though) that this has to remain as it was.

2020-12-27 18:14 UTC, wslany commented on README.md
> +**Catroid** is a visual coding IDE and interpreter for Android Development for the Catrobat programming language.
```suggestion
**Catroid** is a visual coding IDE and interpreter for Android for the Catrobat programming language.
```

2020-12-27 18:14 UTC, wslany commented on README.md
> +**Catrobat** is a visual programming language and a set of creativity tools for smartphones Android apps available on Google Play and iPhone apps available on Apple's app store.
```suggestion
**Catrobat** is a visual programming language and a set of creativity tools for smartphones.
```

2021-01-19 10:33 UTC, closed without merging