CATROID-761 Single undo of editing or creating a look
Catrobat/Catroid pull request #3898
Opened 2020-12-18 17:37 UTC by devsebastian

Ticket: https://jira.catrob.at/browse/CATROID-761

Single undo of editing or creating a look (in paintroid, or on importing from gallery / media library.)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-19 10:34 UTC, ndrnour submitted a review, later dismissed
seems something wrong going on with `showUndoSpinnerSelection` function. please find it out and fix it

```11:31:20  > Task :catroid:compileCatroidDebugJavaWithJavac
11:31:20  /home/catroid/jenkins_slave/workspace/Catroid_PR-3898/catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java:229: error: cannot find symbol
11:31:20  			showUndoSpinnerSelection(false);
11:31:20  			^
11:31:20    symbol:   method showUndoSpinnerSelection(boolean)
11:31:20    location: class SpriteActivity```

2020-12-20 10:13 UTC, devsebastian commented
Thanks @ndrnour!  Don't know why it shows this function as an unknown symbol, although this function is included in the same file, nevertheless, I've updated the code and pushed the changes. Thanks again!

2020-12-26 14:38 UTC, juliajulie95 requested changes
As already discussed with Dev on Slack:
When testing this PR the app crashed when using "undo" after adding a new look through paintroid.
Please have a look at this again.

Error:
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: org.catrobat.catroid, PID: 8001
    ar.com.hjg.pngj.PngjInputException: Could not open /data/user/0/org.catrobat.catroid/files/My project 1/Scene 1/images/Animal.png
        at ar.com.hjg.pngj.PngHelperInternal.istreamFromFile(PngHelperInternal.java:274)
        at ar.com.hjg.pngj.PngReader.<init>(PngReader.java:147)
        at org.catrobat.catroid.utils.ImageEditing.writeMetaDataStringToPNG(ImageEditing.java:231)
        at org.catrobat.catroid.sensing.CollisionInformation.writeCollisionVerticesToPNGMeta(CollisionInformation.java:451)
        at org.catrobat.catroid.sensing.CollisionInformation.createCollisionPolygon(CollisionInformation.java:194)
        at org.catrobat.catroid.sensing.CollisionInformation.loadCollisionPolygon(CollisionInformation.java:134)
        at org.catrobat.catroid.sensing.CollisionPolygonCreationTask.run(CollisionPolygonCreationTask.java:42)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: /data/user/0/org.catrobat.catroid/files/My project 1/Scene 1/images/Animal.png: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at ar.com.hjg.pngj.PngHelperInternal.istreamFromFile(PngHelperInternal.java:272)
        at ar.com.hjg.pngj.PngReader.<init>(PngReader.java:147) 
        at org.catrobat.catroid.utils.ImageEditing.writeMetaDataStringToPNG(ImageEditing.java:231) 
        at org.catrobat.catroid.sensing.CollisionInformation.writeCollisionVerticesToPNGMeta(CollisionInformation.java:451) 
        at org.catrobat.catroid.sensing.CollisionInformation.createCollisionPolygon(CollisionInformation.java:194) 
        at org.catrobat.catroid.sensing.CollisionInformation.loadCollisionPolygon(CollisionInformation.java:134) 
        at org.catrobat.catroid.sensing.CollisionPolygonCreationTask.run(CollisionPolygonCreationTask.java:42) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at ar.com.hjg.pngj.PngHelperInternal.istreamFromFile(PngHelperInternal.java:272) 
        at ar.com.hjg.pngj.PngReader.<init>(PngReader.java:147) 
        at org.catrobat.catroid.utils.ImageEditing.writeMetaDataStringToPNG(ImageEditing.java:231) 
        at org.catrobat.catroid.sensing.CollisionInformation.writeCollisionVerticesToPNGMeta(CollisionInformation.java:451) 
        at org.catrobat.catroid.sensing.CollisionInformation.createCollisionPolygon(CollisionInformation.java:194) 
        at org.catrobat.catroid.sensing.CollisionInformation.loadCollisionPolygon(CollisionInformation.java:134) 
        at org.catrobat.catroid.sensing.CollisionPolygonCreationTask.run(CollisionPolygonCreationTask.java:42) 
        at java.lang.Thread.run(Thread.java:919) 
E/BaseExceptionHandler: uncaughtException: 
    ar.com.hjg.pngj.PngjInputException: Could not open /data/user/0/org.catrobat.catroid/files/My project 1/Scene 1/images/Animal.png
        at ar.com.hjg.pngj.PngHelperInternal.istreamFromFile(PngHelperInternal.java:274)
        at ar.com.hjg.pngj.PngReader.<init>(PngReader.java:147)
        at org.catrobat.catroid.utils.ImageEditing.writeMetaDataStringToPNG(ImageEditing.java:231)
        at org.catrobat.catroid.sensing.CollisionInformation.writeCollisionVerticesToPNGMeta(CollisionInformation.java:451)
        at org.catrobat.catroid.sensing.CollisionInformation.createCollisionPolygon(CollisionInformation.java:194)
        at org.catrobat.catroid.sensing.CollisionInformation.loadCollisionPolygon(CollisionInformation.java:134)
        at org.catrobat.catroid.sensing.CollisionPolygonCreationTask.run(CollisionPolygonCreationTask.java:42)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: /data/user/0/org.catrobat.catroid/files/My project 1/Scene 1/images/Animal.png: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at ar.com.hjg.pngj.PngHelperInternal.istreamFromFile(PngHelperInternal.java:272)
        at ar.com.hjg.pngj.PngReader.<init>(PngReader.java:147) 
        at org.catrobat.catroid.utils.ImageEditing.writeMetaDataStringToPNG(ImageEditing.java:231) 
        at org.catrobat.catroid.sensing.CollisionInformation.writeCollisionVerticesToPNGMeta(CollisionInformation.java:451) 
        at org.catrobat.catroid.sensing.CollisionInformation.createCollisionPolygon(CollisionInformation.java:194) 
        at org.catrobat.catroid.sensing.CollisionInformation.loadCollisionPolygon(CollisionInformation.java:134) 
        at org.catrobat.catroid.sensing.CollisionPolygonCreationTask.run(CollisionPolygonCreationTask.java:42) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at ar.com.hjg.pngj.PngHelperInternal.istreamFromFile(PngHelperInternal.java:272) 
        at ar.com.hjg.pngj.PngReader.<init>(PngReader.java:147) 
        at org.catrobat.catroid.utils.ImageEditing.writeMetaDataStringToPNG(ImageEditing.java:231) 
        at org.catrobat.catroid.sensing.CollisionInformation.writeCollisionVerticesToPNGMeta(CollisionInformation.java:451) 
        at org.catrobat.catroid.sensing.CollisionInformation.createCollisionPolygon(CollisionInformation.java:194) 
        at org.catrobat.catroid.sensing.CollisionInformation.loadCollisionPolygon(CollisionInformation.java:134) 
        at org.catrobat.catroid.sensing.CollisionPolygonCreationTask.run(CollisionPolygonCreationTask.java:42) 
        at java.lang.Thread.run(Thread.java:919) 

2020-12-28 13:32 UTC, juliajulie95 approved these changes

2020-12-28 15:47 UTC, merged

2020-12-28 15:47 UTC, wslany commented
Thanks!!!