CATROID-523 Refactor textwatchers of dialog
Catrobat/Catroid pull request #3903
Opened 2020-12-21 16:26 UTC by Walcho1125

*Please enter a short description of your pull request and add a reference to the Jira ticket.*
Refactor TextWatchers of Dialog, so there is no duplicated code and it also works for the input in "Your Bricks"
https://jira.catrob.at/browse/CATROID-523
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x ] Include the name of the Jira ticket in the PR’s title
- [x ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-30 14:54 UTC, mstoeg requested changes
Please have a look at my remarks and also at the two testcases failing in MergeProjectNameTest.

2020-12-30 14:54 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.java
> +			protected boolean isNameUnique(String name) {
I think you don't need to override this function, as the same functionality is already provided by the base class.

2020-12-30 14:54 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/textwatcher/DuplicateInputTextwatcher.java
> +public class DuplicateInputTextwatcher<T extends Nameable> extends InputWatcher.TextWatcher {
Could you please use camelCase for TextWatcher to stay consistent here.

2020-12-30 14:54 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/textwatcher/DuplicateInputTextwatcher.java
> +	private void getScopeFromoriginalScope() {
Also please use camelCase here for OriginalScope.

2020-12-30 14:54 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/merge/NewProjectNameTextWatcher.java
> +		return ReplaceExistingProjectDialogFragment.projectExistsInDirectory(name);
I think there is some kind of logic inversion here, which also leads to the failing testcases. If a project does exist it is NOT unique.

2020-12-31 11:58 UTC, Walcho1125 commented
@mstoeg Thanks for reviewing, all requested changes should be applied now

2020-12-31 14:59 UTC, mstoeg approved these changes
Well done - looks good now!

2021-01-02 13:43 UTC, merged

2021-01-02 13:43 UTC, wslany commented
Thanks!