CATROID-760 Fast Loops
Catrobat/Catroid pull request #3908
Opened 2020-12-26 13:34 UTC by blindguardian50

Execute loop delays only if specific bricks are contained within
https://jira.catrob.at/browse/CATROID-760

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-30 18:30 UTC, adnaribo approved these changes

2020-12-30 23:23 UTC, wslany requested changes
The loops correctly remain slowed down if, for instance, a "Next look" brick is used _directly_ in a loop. However, as soon as the "Next look" brick is _inside_ another nested brick or loop, e.g., in an "If then endif" brick, where the condition is true, i.e., where the "Next look" brick is executed during _each_ iteration, the loop delay nevertheless is **_incorrectly_** ignored.

E.g., the values of the variables x and y reported after running the stage a few seconds and then looking up the values in the formula editor for the following two loops, _incorrectly_ are the same. Correct would be that the number reported for the loop with the "Next look" brick should be much _lower_ (in the same amount of time).
![image](https://user-images.githubusercontent.com/1747888/103386089-77adeb00-4afd-11eb-8624-5fd5b318a604.png)
![image](https://user-images.githubusercontent.com/1747888/103386104-84cada00-4afd-11eb-8b1a-a8d9a6b80689.png)

![image](https://user-images.githubusercontent.com/1747888/103386163-dbd0af00-4afd-11eb-8da3-f95ee4fefdde.png)

Here the reported numbers if the "Next look" is outside of the nested "If then endif" brick, but still in the loop:
![image](https://user-images.githubusercontent.com/1747888/103386233-3964fb80-4afe-11eb-95d6-063b5ac4d6ce.png)

![image](https://user-images.githubusercontent.com/1747888/103386269-58638d80-4afe-11eb-8571-6ee76ec8c805.png)

2021-01-01 20:28 UTC, adnaribo approved these changes

2021-01-02 21:05 UTC, wslany requested changes
Please reduce the amount of duplicate code: 6 times the same block of 40+ lines that checks the loop delay. This could lead to divergent, difficult to maintain code if the parts are edited non-uniformly. See https://medium.com/grensesnittet/the-key-to-eliminating-duplicated-code-patterns-ddd23b958ded

2021-02-09 17:28 UTC, closed without merging