CATROID-744 - Change Login dialog options
Catrobat/Catroid pull request #3909
Opened 2020-12-27 12:31 UTC by atharva137

**Description**
Added cancel button on login dialog options.

**Jira Ticket Reference** :  https://jira.catrob.at/browse/CATROID-744

Attached Screenshot for the same.
![login_Dialog_screen](https://user-images.githubusercontent.com/70437002/103170826-56cf6680-486d-11eb-8f25-90d023d7d233.png)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-01-06 12:13 UTC, juliajulie95 commented
Please also push the changes you did for fixing the tests (:

2021-01-07 19:38 UTC, atharva137 commented
Hi julia Herold Ma'am  , Yes I have pushed the changes for all the Login Test cases .

2021-01-09 07:18 UTC, atharva137 commented
@juliajulie95 
Hello Julia Herold Ma'am, I'm attaching screenshot to my previous comment . Please find it
![LoginScreen](https://user-images.githubusercontent.com/70437002/104085904-fe3e9700-5278-11eb-8735-4c2af0321e2a.png)

2021-01-09 08:38 UTC, juliajulie95 commented
Thank you, I will review it roday

2021-01-09 12:05 UTC, juliajulie95 requested changes
Please fix the linter warnings: https://jenkins.catrob.at/job/Catroid/job/PR-3909/9/analysis/
If you need any help with this, message me please (:

2021-01-09 18:00 UTC, atharva137 commented
@juliajulie95 
Hi Julia Herold Ma'am,  I have fixed  the linter warnings. Please review . 
Thank and Regards,
Atharva

2021-01-10 16:10 UTC, juliajulie95 requested changes
Thank you for your work!
Please delete the "?" after "reset password", because it is not a question but an action.
Everything else looks good to me and I will approve the pull request after this change.

2021-01-10 16:10 UTC, juliajulie95 commented on catroid/src/main/res/values/strings.xml
> +    <string name="reset_password">Reset password?</string>
Please delete the "?" afterwards

2021-01-10 17:21 UTC, atharva137 commented
Hi @juliajulie95  ma'am,  I have deleted the "?" after "reset password" . please review. Attaching screenshot for the same.  Thank You !! - Atharva.

![ResetPassword](https://user-images.githubusercontent.com/70437002/104130369-4a332e00-5396-11eb-968b-961730c9d533.png)

2021-01-10 18:48 UTC, juliajulie95 approved these changes

2021-01-10 18:49 UTC, juliajulie95 commented
Please push the ticket in jira dashboard to in code review (:

2021-01-10 19:10 UTC, atharva137 commented
Hi @juliajulie95  Ma' am , I am trying to change the status from " Under Development"  to "Code Review" , but not able to update it .Could you please help me in this .

Thanks and Regards,
Atharva

2021-01-21 08:28 UTC, merged

2021-01-21 08:28 UTC, wslany commented
Thanks @atharva137 !

2021-01-21 08:54 UTC, wslany commented
Awesome, the OutgoingNetworkCalls now also are green again!!!!
![image](https://user-images.githubusercontent.com/1747888/105326966-a2f09b00-5bce-11eb-8d6a-3f40fb7cd779.png)