CATROID-860 Face detection sensors do not work with the rear camera
Catrobat/Catroid pull request #3921
Opened 2021-01-02 18:48 UTC by devsebastian

This PR should solve the bugs described in tickets: 
1. https://jira.catrob.at/browse/CATROID-860
2. https://jira.catrob.at/browse/CATROID-777

combined the text and face Detector to run simultaneously on the same imageAnalyser instead of running on different instances. (this also makes it possible to run text detection and face detection simultaneously as was not the case before)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-01-22 12:55 UTC, adnaribo requested changes
Everytime I Start the script from https://jira.catrob.at/browse/CATROID-860 I get the Toast on the stage "There was a problem withtext detection ..... ". And could you please look at the failing jenkins test. Everything else is working just fine, good work :+1:

2021-01-28 18:23 UTC, adnaribo requested changes
Could you please change in the files you touched (if it's not already changed) in line 3  "2010-2020" to 2010-2021. Thank you :1st_place_medal:

2021-01-28 19:00 UTC, adnaribo approved these changes

2021-02-06 09:01 UTC, merged

2021-02-06 09:02 UTC, wslany commented
Thanks!