CATROID-876 Allow to edit bricks in Catblocks
Catrobat/Catroid pull request #3924
Opened 2021-01-04 19:05 UTC by bprattes

https://jira.catrob.at/browse/CATROID-876
Now it is possible to edit bricks in Catblocks (add, remove, move, duplicate).
Therefore each brick has its own unique ID.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-01-09 13:06 UTC, juliajulie95 requested changes
https://jenkins.catrob.at/job/Catroid/job/PR-3924/9/analysis/
One string is unused, please delete it

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/DummyBrick.kt
> +        // do nothing
delete comment.
If lint acts up add a ignore

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
> +		for (Brick b : cb.getNestedBricks()) {
variable name b - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
> +		CompositeBrick cb = (CompositeBrick) this;
variable name

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
> +		int idx = 0;
variable name. Is it a typo of id?

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
> +			for (Brick b : cb.getSecondaryNestedBricks()) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
> +		for (Brick b : cb.getNestedBricks()) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/BrickBaseType.java
> +		CompositeBrick cb = (CompositeBrick) this;
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Sprite.java
> +		for (Script s : scriptList) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Script.java
> +		for (Brick b : brickList) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Script.java
> +			for (Brick b : brickList) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Script.java
> +			int idx = 0;
variable name

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Script.java
> +		// only if the sub stack index is -1, the brick can be a direct child of the script brick
no comments pls

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Script.java
> +			for (Brick b : bricks) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/Script.java
> +		for (Brick b : brickList) {
variable name - no abbreviations please

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/content/DummyScript.kt
> +        // do nothing
pls delete

2021-01-09 13:06 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/AddBrickCatblocksTest.java
> +			// it may take some time until the brick appears in Catblocks, so try multiple times
pls delete

2021-02-09 17:00 UTC, juliajulie95 requested changes

2021-02-09 17:00 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/app/AddBrickCatblocksTest.java
> +				Fragment f = FragmentManager.findFragment(v);
abbreviations

2021-02-09 17:00 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CatblocksScriptFragment.kt
> +        private fun locateBrickInSprite(sprite: Sprite, brickId: UUID): BrickHelper? {
duplicate code?

2021-02-09 17:00 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
> +		// ensure scrolling only once
comment

2021-02-10 06:19 UTC, juliajulie95 approved these changes

2021-02-17 17:12 UTC, merged

2021-02-17 17:12 UTC, wslany commented
Thanks!