"name already exists" logic reversed when downloading existing project
Catrobat/Catroid pull request #3946
Opened 2021-01-22 16:34 UTC by dandrawes

https://jira.catrob.at/browse/CATROID-881
- allow to name projects with a not used name when downloading an existing project

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-01-23 12:58 UTC, mstoeg reviewed
Please have a look at my remarks and fix them. Moreover, there the red error message hint of the duplicate project name does not appear in the beginning - it seems that the validation is not triggered when opening the dialog. Only if I add a character and remove it afterwards the error message is shown.

2021-01-23 12:58 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/ReplaceExistingProjectDialogFragment.java
> +				return !projectExistsInDirectory(name) || GlobalProjectDownloadQueue.INSTANCE.getQueue().alreadyInQueue(name);
I think there is still some kind of inversed logic here. Either you negate the whole term or you have to use 
`return !projectExistsInDirectory(name) && !GlobalProjectDownloadQueue.INSTANCE.getQueue().alreadyInQueue(name);` which is basically equivalent to that.

2021-01-23 12:58 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/ReplaceExistingProjectDialogFragment.java
> -						break;
I know that this does not concern this ticket, however there seems to be an issue with the keyboard popping up when you change the selection of the radio button. Please add following code here:
`ViewUtils.hideKeyboard(inputLayout.getEditText());`

2021-01-23 12:58 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/ReplaceExistingProjectDialogFragment.java
> -								.setEnabled(textWatcher.validateInput(inputLayout.getEditText().toString(), getContext()) == null);
Vice verca show the keyboard again here with: 
`ViewUtils.showKeyboard(inputLayout.getEditText());`

2021-01-23 12:58 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/ReplaceExistingProjectDialogFragment.java
> +		alertDialog.setOnShowListener(dialog -> {
Please remove this method as it is just duplicate code (have a look at the `TextInputDialog.Builder` class where the same functionality is already implemented.

2021-01-25 09:00 UTC, mstoeg reviewed
Well done! Just some minor improvements can be done. (as discussed in Slack)

2021-01-25 10:56 UTC, mstoeg approved these changes
Looks good now - thank you!

2021-01-26 04:11 UTC, wslany requested changes
Thanks! Please add a regression test.

2021-01-27 14:35 UTC, mstoeg approved these changes
Testcases added in pair programming.

2021-01-28 10:48 UTC, wslany approved these changes

2021-01-28 10:48 UTC, merged

2021-01-28 10:48 UTC, wslany commented
Thanks!