CATROID-827 Help links to wiki in formula editor
Catrobat/Catroid pull request #3955
Opened 2021-02-01 12:43 UTC by ChriMoser

[CATROID-827](https://jira.catrob.at/browse/CATROID-827)
Added a button on the top bar of the Functions/Sensors/Logic/Properties submenus in the formula editor which opens the browser with the wiki page corresponding to the current submenu.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-02-16 13:07 UTC, Walcho1125 requested changes
Well done! 
Please take a look at the remarks and change them like discussed. Also, update the copyright range in every changed file.

2021-02-16 13:07 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
> +		}
why switch with 1 case?

2021-02-16 13:07 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/CategoryListFragment.java
> +				return Constants.CATROBAT_SENSORS_WIKI_URL;
Please also include the corresponding language to your helpurl from the sharedpreferences (see settingsfragment for getting language tag)

2021-03-04 08:22 UTC, Walcho1125 approved these changes
Looks good to me now, Well done!

2021-03-20 00:41 UTC, merged

2021-03-20 00:41 UTC, wslany commented
THanks!