CATROID-742 Add Placeholder names
Catrobat/Catroid pull request #3973
Opened 2021-02-08 15:04 UTC by Walcho1125

*Please enter a short description of your pull request and add a reference to the Jira ticket.*
Add placeholder to any add option https://jira.catrob.at/browse/CATROID-742
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-02-11 07:32 UTC, sasalala000 approved these changes

2021-02-16 00:10 UTC, dandrawes requested changes
Well done!

Please look at my small remarks and change the year range in the header to "2021" in the changed files.

The first new object is named "My actor or object" without "(1)" in the end like all other placeholders, please change this also to be consistent.

2021-02-16 00:10 UTC, dandrawes commented on catroid/src/main/java/org/catrobat/catroid/ui/SpriteActivity.java
> +				TextInputEditText textInputEditText = alertDialog.findViewById(R.id.input_edit_text);
Deduplicate the same code in both branches.

2021-02-18 18:21 UTC, dandrawes approved these changes
Looks good now!

2021-03-04 09:57 UTC, wslany requested changes
Two failing tests remain, see comments. 

Please recheck the point "Confirm that new and existing unit tests pass locally".

2021-03-04 09:57 UTC, wslany commented on catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectUnzipAndImportTaskTest.java
> +	private static final String AIR_FIGHT_0_5 = "Air fight 0.5 (1)";
This leads to a failure in line 89 further below.

Stacktrace:
https://jenkins.catrob.at/job/Catroid/job/PR-3973/51/testReport/org.catrobat.catroid.test.io.asynctask/ProjectUnzipAndImportTaskTest/All___1___Instrumented_Unit_Tests___testUnzipAndImportSingleProject/

=>
```
java.lang.AssertionError:
Expected: a collection containing "Air fight 0.5 (1)"
but: was "Air fight 0.5"
at org.catrobat.catroid.test.io.asynctask.ProjectUnzipAndImportTaskTest.testUnzipAndImportSingleProject(ProjectUnzipAndImportTaskTest.java:89)
```

2021-03-04 09:57 UTC, wslany commented on catroid/src/androidTest/java/org/catrobat/catroid/test/io/asynctask/ProjectUnzipAndImportTaskTest.java
> +	private static final String FALLING_BALLS = "Falling balls (1)";
This leads to a failure in line 104 further below.

Stacktrace:
https://jenkins.catrob.at/job/Catroid/job/PR-3973/51/testReport/org.catrobat.catroid.test.io.asynctask/ProjectUnzipAndImportTaskTest/All___1___Instrumented_Unit_Tests___testUnzipAndImportMultipleProjects/
=>
```
java.lang.AssertionError:
Expected: a collection containing "Falling balls (1)"
but: was "Air fight 0.5", was "Air fight 0.5 (1)", was "Falling balls"
at org.catrobat.catroid.test.io.asynctask.ProjectUnzipAndImportTaskTest.testUnzipAndImportMultipleProjects(ProjectUnzipAndImportTaskTest.java:104)
```

2021-03-04 12:40 UTC, Walcho1125 commented
> Two failing tests remain, see comments.
> 
> Please recheck the point "Confirm that new and existing unit tests pass locally".

I fixed the Problem and reran the all tests locally to make sure that all pass

2021-03-04 13:07 UTC, wslany approved these changes

2021-03-04 13:11 UTC, merged

2021-03-04 13:11 UTC, wslany commented
Thanks!