CATROID-862 Incorrect elimination of "f" and "d" behind numbers in strings
Catrobat/Catroid pull request #3974
Opened 2021-02-08 21:27 UTC by Rawbat

Fixed this by adding a check if those chars are contained in the string in the tryParseDouble Function.
Also removed the normal double cast in the set variable action and replaced it with a function call to this.

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-02-17 17:42 UTC, Koell requested changes
currently the CTL would also wrongfully work for floats or double ending with upper "F/D"
direkt comparisons cast the variables to double as possible which is the correct behaviour, to check if the float is still stored as a float regexes work quiete nicely

2021-02-17 17:42 UTC, Koell commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/common/Conversions.kt
> +        }
please replace the if with 
`if (argument.matches(Regex("[fFdD]\$"))){`
as currently the usecase ("F") which promptet this task is ignored

2021-02-22 21:08 UTC, Koell approved these changes

2021-02-22 21:08 UTC, Koell commented
Thanks for the work

2021-02-26 14:46 UTC, wslany requested changes
Nice! Please can you fix the lint warning? 

=> https://jenkins.catrob.at/job/Catroid/job/PR-3974/13/analysis/source.d38fecc7-1338-48fd-9893-2c094f2bd35f/#35

2021-02-27 02:12 UTC, wslany approved these changes

2021-02-27 02:12 UTC, merged

2021-02-27 02:12 UTC, wslany commented
Thanks!