CARTOID-817
Catrobat/Catroid pull request #3982
Opened 2021-02-13 10:35 UTC by devsebastian

Ticket: https://jira.catrob.at/browse/CATROID-817

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-02-23 12:18 UTC, adnaribo requested changes
Please check what is written under data in the formula editor for the values for the input of the user defined brick, see screenshot below. 
![image](https://user-images.githubusercontent.com/48415989/108840513-c1372580-75d6-11eb-8a7d-433836e272b9.png)
Even after executing the CTL of this ticket there are the IDs in the data field of the formula editor, see screenshot below.
![image](https://user-images.githubusercontent.com/48415989/108842479-a0bc9a80-75d9-11eb-960f-cf2c638e7566.png)

2021-03-05 06:45 UTC, mstoeg commented on catroid/src/main/java/org/catrobat/catroid/content/UserDefinedScript.java
> +		return null;
In order to make the value part of the DataListAdapter display a value please change the Adapter for the User Defined Bricks from `UserDataRVAdapter` back to `UserDefinedBrickInputRVAdapter`. This class already exists, but somehow wasn't used any more. In the `UserDefinedBrickInputRVAdapter` class change the position where the value is extracted inside the `onBindViewHolder` method like this: 
```
	@Override
	public void onBindViewHolder(CheckableVH holder, int position) {
		super.onBindViewHolder(holder, position);

		UserDefinedBrickInput item = items.get(position);
		VariableVH variableVH = (VariableVH) holder;
		variableVH.title.setText(item.getName());
		int value;
		try {
			value = ((Formula) item.getValue()).interpretInteger(null);
		} catch (InterpretationException e) {
			value = 0;
		}
		variableVH.value.setText(toMetricUnitRepresentation(value));
	}
```

2021-03-08 13:33 UTC, adnaribo approved these changes
Looks good, thank you very much :1st_place_medal:

2021-03-16 17:39 UTC, merged

2021-03-16 17:39 UTC, wslany commented
Thanks!!