CATROID-852 Rename General Properties to Look Properties
Catrobat/Catroid pull request #4009
Opened 2021-03-10 17:39 UTC by CodeChamp-SS

Renamed General Properties to Look Properties in the Properties list in the formula editor.

<img src="https://user-images.githubusercontent.com/52480794/110671851-ffe2f780-81f4-11eb-8842-ca1502599535.png" width="400" height="700"/>

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-03-17 10:54 UTC, Walcho1125 approved these changes
Thank you, well done!

2021-03-19 13:38 UTC, wslany requested changes
Please also rename the id name.

2021-03-19 13:38 UTC, wslany commented on catroid/src/main/res/values/strings.xml
> +    <string name="formula_editor_object_general">Look properties</string>
```suggestion
    <string name="formula_editor_object_look">Look properties</string>
```

2021-03-19 13:57 UTC, CodeChamp-SS commented on catroid/src/main/res/values/strings.xml
> +    <string name="formula_editor_object_general">Look properties</string>
done : )

2021-03-20 01:23 UTC, wslany requested changes
Please fix the compile errors.

2021-03-20 04:29 UTC, CodeChamp-SS commented
> Please fix the compile errors.

done, please do lemme know if any further changes are required.

2021-03-20 07:58 UTC, Walcho1125 approved these changes
Thank you !

2021-03-20 07:59 UTC, wslany approved these changes

2021-03-20 07:59 UTC, merged

2021-03-20 07:59 UTC, wslany commented
Thanks!