CATROID-962 Catrobat Language Test for "wait" brick
Catrobat/Catroid pull request #4013
Opened 2021-03-12 09:32 UTC by frit96

https://jira.catrob.at/browse/CATROID-962

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-03-13 13:48 UTC, petbuer commented
Thanks. 👍 
However, the problem is that the wait brick is really hard to test. First, if you wanted to test the correct timing, you would need a separate time source to validate the result. Second, synchronization is not ensured, since there's no guarantee in which order the "When scene starts" scripts are executed, and which bricks are executed first in an interlaced, multithreaded order. In general, waits should be avoided in language tests, since they can cause flakyness on slow emulators (e.g. Jenkins).

2021-03-20 11:13 UTC, petbuer approved these changes

2021-03-20 20:14 UTC, wslany requested changes
Thanks, but unfortunately Catrobat is not clever enough to understand the transitivity of numerical comparisons. So `0.8 < timer < 1.2` actually would be also true if timer would be 100, since the `true` resulting from `0.8 < timer` is then cast to the number 1 because there's a numerical comparison of `true < 1.2`, and 1 is smaller than 1.2, so altogether it is `true`. Similarly, `0.8 < 10000 < 1.2` is also evaluated to true in Catrobat even though this clearly is mathematically incorrect (but this is also the incorrect behavior in other programming languages).

Thus, please replace the formula for this test by  `0.8 < timer and timer < 1.2` to test as you intended it.

However, I have seen similar formulas written by our young users, so I think we need to somehow handle that in the future, and also it would be cool. It makes much more sense to handle it like it is normally handled in math, i.e., like you wrote it, than how Catrobat interpreted it. What to do? We could add a kind of wizard that detects "transitively chained" logical formulas and offers to rewrite them with "and"s in between. What do you think?

2021-03-22 12:09 UTC, petbuer approved these changes

2021-03-22 15:00 UTC, wslany approved these changes

2021-03-22 15:00 UTC, merged