CATROID-958 Textblock detection x and y sensors return the wrong value
Catrobat/Catroid pull request #4017
Opened 2021-03-13 16:57 UTC by ritiksp2411

Changed the value of the sensor variable X to Y and Y to -X.

https://jira.catrob.at/browse/CATROID-958

I tested the work on the Honor 9i android device.
 
Signed-off-by: ritiksp2411 <ritik.rjt@gmail.com>

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-03-16 14:15 UTC, qlin93 commented
Thanks for making the changes. 
I tested your changes with this test:
![testTextblockDetection](https://user-images.githubusercontent.com/26432083/111322825-9dad4b00-8669-11eb-8723-d818264fb6e6.jpeg)
and the returned coordinates are not on the screen. The X should be exactly where the text is that is being detected. 
Have a look at FaceAndTextDetector.kt, where the coordinate translation is implemented correctly. You also need to check how it works when using the front camera. Please make the necessary changes and amend your commit.

2021-03-17 07:13 UTC, ritiksp2411 commented
Thanks for the review, 
I have one doubt like we have a bug in landscape mode right, but the screenshot is in Portrait mode? I didn't get that part.

2021-03-17 09:15 UTC, ritiksp2411 commented
In the file FaceAndTextDetector.kt, we have Y as X if the camera is facing front, and Y as 1-X if not.
Along with that if we have oldAPI, then X is Y otherwise, X is 1-Y. So do I need to check oldAPI too right?

2021-03-20 11:52 UTC, qlin93 commented
Thanks. Creating a project in landscape mode does not change the orientation of the Pocket Code app itself only of the project when it is run.

Yes please also take the oldAPI into account.  
Have you installed the app via Android Studio to test the changes you made? 
This is important because the solution for TextblockUtil might not be exactly the same as for the FaceAndTextDetector, 
as the x and y might be different. (It could have different origins)

2021-03-21 05:06 UTC, ritiksp2411 commented
thanks, I check the changes in my phone but couldn't recognize that properly, now I will make the changes and update accordingly.

2021-03-25 13:16 UTC, ritiksp2411 commented
When I tested with your test, I have noticed that returned coordinates of the X are sometimes on the screen and sometimes off the screen. Any specific reason for that?

2021-03-25 14:16 UTC, ritiksp2411 commented
![WhatsApp Image 2021-03-25 at 7 45 36 PM](https://user-images.githubusercontent.com/48794096/112487510-c5f02480-8da2-11eb-972a-e1cb4932b083.jpeg)
It is showing the X properly now.

2021-03-26 11:07 UTC, qlin93 commented
Looks good. Please push your changes on this branch by amending your commit.

2021-03-26 16:13 UTC, ritiksp2411 commented
Thanks for helping, I updated the PR.

2021-04-06 10:53 UTC, qlin93 requested changes
Hi sorry for the delay. Unfortunately it still does not work correctly. When a text is detected and you move your camera around the x and y coordinates or in the example testcase the X should follow the text. With the change you made the problem still persists, the movement along the x-axis is shown on the y-axis and vice versa.

2021-04-06 15:13 UTC, ritiksp2411 commented
okay, yeah so the shift of X was shown in Y, but bow I Fixed it such that when we move our camera left side that means Text in the image will go right and the same will be shown by X on the screen. Similarly, if we move the camera upwards, the text in the image will go down and the same will be shown by X on the screen.

2021-04-08 11:40 UTC, qlin93 requested changes
Thanks, that is better but the movement on the axes are still inverted and the scaling is off. I looked into the issue more closely and it turned out to be a little more complicated to fix than stated in the ticket. 

Please apply the suggested changes and test whether they work on your device before updating your commit.

2021-04-08 11:40 UTC, qlin93 commented on catroid/src/main/java/org/catrobat/catroid/utils/TextBlockUtil.java
> +					relativeY = invertAxis ? 1 - relativeY : relativeY;
```suggestion
					float relativeX = textBlockBounds.exactCenterX() / imageWidth;
					relativeX = invertAxis ? 1 - relativeX : relativeX;
```

2021-04-08 11:40 UTC, qlin93 commented on catroid/src/main/java/org/catrobat/catroid/utils/TextBlockUtil.java
>  							(float) SCREEN_WIDTH
```suggestion
							relativeX,
							SCREEN_WIDTH,
							1 - textBlockBounds.exactCenterY() / imageHeight,
							(float) SCREEN_WIDTH / aspectRatio
```

2021-04-09 05:25 UTC, ritiksp2411 commented
Thanks for the suggestion, I saw that it exactly behaves the same as my previous PR, like axis are behaving the same way. I am unable to justify scaling there but ya, the axis are working in the same manner.

2021-04-09 10:53 UTC, qlin93 commented
I tested it again and you are right the axes are behaving the same way, but the scaling is completely off. I cannot approve something that does not work correctly and you should always test and make sure that the behaviour is exactly as it should be.
In this case the returned coordinates should be exactly in the center of the text.  

Here are some screenshots I took while testing. 

With the existing changes: 
https://drive.google.com/file/d/1OMjYDEh03vS4Rflgldxu5ruN8qzsN7uK/view?usp=sharing
https://drive.google.com/file/d/12aaEzku-waJbM_BHLTA3g5oBf_O4pKG9/view?usp=sharing

With suggested changes: 
https://drive.google.com/file/d/1SPbV4IUhP4bC6CRjCtLW-iRux71CgdN_/view?usp=sharing
https://drive.google.com/file/d/1fu0pbYGCF2lXVn19H2psCJqQpdOFv_eh/view?usp=sharing

2021-04-09 11:59 UTC, ritiksp2411 commented
Thanks for the insight and for helping me out. I will change the code as suggested and update the PR soon.

2021-04-10 10:17 UTC, qlin93 requested changes
Thanks just a small error, please change imageWidth to imageHeight in line 110.

2021-04-10 10:17 UTC, qlin93 commented on catroid/src/main/java/org/catrobat/catroid/utils/TextBlockUtil.java
> +							1 - textBlockBounds.exactCenterY() / imageWidth,
```suggestion
							1 - textBlockBounds.exactCenterY() / imageHeight,
```

2021-04-11 10:10 UTC, qlin93 approved these changes
Thanks!

2021-04-11 12:29 UTC, ritiksp2411 commented
Thanks for helping,
Learned a lot from the issue

2021-04-21 05:41 UTC, merged

2021-04-21 05:42 UTC, wslany commented
Thanks a lot!!