CATROID-831 Add a search tool to scripts view
Catrobat/Catroid pull request #4019
Opened 2021-03-14 20:14 UTC by devsebastian

Ticket: https://jira.catrob.at/browse/CATROID-831

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-03-14 20:17 UTC, devsebastian commented
I've used a different approach than what is discussed in the ticket and it work's perfectly fine at the moment, let me know if the current approach needs to be improved or changed! Happy to update the code accordingly

2021-03-26 09:22 UTC, Walcho1125 requested changes
Well done! 
Please resolve the conflicts that occur. Additionally please remove the find option from the Category view when adding a brick, since the search option should only be available in the script view.
Best Regards!

2021-03-30 12:18 UTC, Walcho1125 approved these changes
Well done, looks good to me!

2021-03-30 13:51 UTC, wslany requested changes
Thanks! Great that it works with the translated formula content!!

Currently the search only works in the current object's scripts. Instead, it should search through all objects in all scenes, and thus also jump to another object and place in scripts where the phrase is found.

Also please search through pull-down type (spinner) parameter fields such as names of scenes, objects, variables, lists, broadcast messages, instruments, drums, looks, backgrounds, or sounds.

Also, if it is easy, please make the search case insensitive (unicode character encoding based if supported, see https://developer.android.com/reference/java/util/regex/Pattern#UNICODE_CASE --- for regular expressions it is possible to use the (?u) prefix).

2021-03-30 13:51 UTC, wslany commented on catroid/src/main/res/values/strings.xml
> +    <string name="find_next">Find Next %d/%d</string>
```suggestion
    <string name="find_next">Find next %d/%d</string>
```

2021-04-09 09:28 UTC, Walcho1125 requested changes
Please take a look at my small remarks, the functionality works out good!

2021-04-09 09:28 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
> +//                    currentSprite.getName()));
please remove that out commented code

2021-04-09 09:28 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ScriptFragment.java
> +			case FIND:
break is missing

2021-04-09 12:27 UTC, Walcho1125 submitted a review, later dismissed
Please resolve the merge conflicts!

2021-04-10 08:38 UTC, Walcho1125 approved these changes
well done! looks good to me now

2021-04-21 04:04 UTC, wslany requested changes
Hi Dev, after trying the interface, I found the checkmark button not intuitive --- I kept tapping on it to start the search. How about the following: Instead of the checkmark, move the search field and the magnification icon into the top bar. The "Find keyword" should be replaced by a larger text field. Like now, the v and ^ buttons replace the magnification button once more than one result has been found to navigate among the results. What do you think? I believe it is still material design conform, since I have seen similar ways to place the search field in several other apps as well. I.e., 
![image](https://user-images.githubusercontent.com/1747888/115495151-55d0a380-a267-11eb-80a6-fb43e7867cb6.png)

2021-04-25 17:01 UTC, wslany approved these changes

2021-04-25 17:02 UTC, merged

2021-04-25 17:02 UTC, wslany commented
Thanks!!!

2021-04-26 11:54 UTC, mstoeg commented
I think this ticket introduced a failing testcase `testForToast()` in the `SystemOutTest.java` file. @devsebastian could you please have a look at it and fix it? It is because of the Toast messages you added in the `ScriptFinder`.

2021-04-26 16:09 UTC, devsebastian commented
> I think this ticket introduced a failing testcase `testForToast()` in the `SystemOutTest.java` file. @devsebastian could you please have a look at it and fix it? It is because of the Toast messages you added in the `ScriptFinder`.

On it 👍