ticker - CATROID-847
Catrobat/Catroid pull request #4099
Opened 2021-04-08 03:53 UTC by vinayak0505

just added a scrollchangelistner in scriptFragment to hide the fab when last item is visible for 2000 millisecond.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-04-09 09:43 UTC, vinayak0505 commented
Can please check this pull@juliajulie95 @wslany

2021-04-10 12:21 UTC, wslany commented
https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines are not followed.

2021-04-11 13:48 UTC, vinayak0505 commented
@wslany is it okay now

2021-04-13 12:11 UTC, vinayak0505 commented
@wslany please review this pull request

2021-04-17 02:46 UTC, wslany requested changes
Please add automatic test cases that check the new functionality.

2021-04-17 02:57 UTC, vinayak0505 commented
@wslany right now I don't know how to make test cases, but still 8 squash the commits

2021-04-17 11:51 UTC, wslany commented
Thanks. Please, can you try to find out how to test? LMK if you find something.

2021-04-17 11:52 UTC, vinayak0505 commented
Sure, I'll give it a try

2021-04-25 14:43 UTC, wslany requested changes
Hi, and many thanks! 🙏 Please fix the lint warnings in https://jenkins.catrob.at/job/Catroid/job/PR-4099/5/analysis/ and also the failing tests, see https://jenkins.catrob.at/job/Catroid/job/PR-4099/5/testReport/ and tap on the individual lines to see the failures or stack traces.

2021-04-25 15:55 UTC, vinayak0505 commented
I have made lint changes also added test code for my code but some test are going to fail even if i don't make changes, I have tried them, i you want i can try fixing them. Let me know if i am missing something or going in the wrong direction

2021-07-13 14:18 UTC, juliajulie95 commented
@vinayak0505 Are you still working on this?

2021-07-13 14:21 UTC, vinayak0505 commented
I pushed the code , I even added the unit test , but it was, later I found all unit test were failing , I mentioned this on jira but there was no response.

2021-07-13 14:24 UTC, vinayak0505 commented
Ill try one more time within this week , of I am not able to do it then I let you know

2021-07-18 17:07 UTC, closed without merging

2021-07-18 17:08 UTC, vinayak0505 commented
@juliajulie95 please check #4265, I have created another pull request with updated code