CATROID-768 "Become focus point with __ % horizontal and __ % vertica…
Catrobat/Catroid pull request #4108
Opened 2021-04-12 13:37 UTC by frit96

…l flexibility" brick

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-01 13:17 UTC, blindguardian50 requested changes
Good Work! Please consider my suggested changes!

2021-07-01 13:17 UTC, blindguardian50 commented on catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
> +	private Sprite spriteToFocusOn = null;
Please take all changes you made in the StageListener and put it into a seperateClass as the StageListener class already has lots of code in it. You can then create a new member of this class for the StageListener and there call the methods.

2021-07-01 13:17 UTC, blindguardian50 commented on catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
> +	public void calculateCameraPositionForFocusedSprite() {
Please rename to:
```suggestion
	public void updateCameraPositionForFocusedSprite() {
```
as the word calculate does not imply any action only a calculation.

2021-07-01 13:17 UTC, blindguardian50 commented on catroid/src/main/java/org/catrobat/catroid/stage/StageListener.java
> +	public void setSpriteToFocusOn(Sprite spriteToFocusOn) {
You won't need the setters if you extract your changes into a seperate kotlin class.

2021-07-27 10:29 UTC, blindguardian50 approved these changes
Nice Work!

2021-08-17 16:29 UTC, wslany commented
Please rebase and resolve th conflicts.

2021-08-19 13:01 UTC, frit96 commented
I rebased and solved the conlicts

2021-08-21 07:52 UTC, merged

2021-08-21 07:52 UTC, wslany commented
Thanks!!