CATROID-1045 Boolean "stage is touched" reporter sensor is false in certain deterministic situations even though the stage is touched
Catrobat/Catroid pull request #4154
Opened 2021-04-24 14:35 UTC by frit96

https://jira.catrob.at/browse/CATROID-1045

Fixed bug with the "stage is touched" sensor

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-04-27 08:37 UTC, blindguardian50 requested changes

2021-04-27 08:37 UTC, blindguardian50 commented on catroid/src/main/java/org/catrobat/catroid/utils/TouchUtil.java
> +	public static double isFingerTouching(double index) {
Please do not change the bahaviour of the function here. There are two stageIsTouched sensors, one with parameter for the index, one without parameter. You were correct with making a new function for the one without parameter. The one with parameter however should stay the same and give information if a specific finger is still on the screen.

2021-04-29 07:13 UTC, blindguardian50 approved these changes
Nice!

2021-05-14 18:42 UTC, merged

2021-05-14 18:42 UTC, wslany commented
Thanks!