CATROID-1033 Velocity is not updated when Actor/object is gliding
Catrobat/Catroid pull request #4178
Opened 2021-05-11 13:28 UTC by Rawbat

Fixed the bug by adding a PhysicsObject to the glideToAction and setting the velocity correctly.

https://jira.catrob.at/browse/CATROID-1033

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-16 15:11 UTC, petbuer approved these changes

2021-06-22 03:50 UTC, wslany requested changes
Great, thanks. Small request only, please change the Cabtrobat language test (CLT) to the following script 
![image](https://user-images.githubusercontent.com/1747888/122859407-4845a180-d31c-11eb-96d0-e3e733e5e8bc.png)

You can also download the CLT (with a smaller look for the sprite) from https://share.catrob.at/app/project/8b0039bf-d30a-11eb-ae11-005056a36f47 if you add `BuildType/debug` to the user agent of your browser. This can be done in Chrome if you right-click on the page, select "Inspect", then on the bottom right select "Network conditions", unselect "Use browser default", then insert `BuildType/debug` in the custom user agent, and then reload the page. Voilà!
![image](https://user-images.githubusercontent.com/1747888/122859989-36b0c980-d31d-11eb-8d06-dc2d89fab9a1.png)

2021-08-17 16:27 UTC, wslany approved these changes

2021-08-17 16:27 UTC, merged

2021-08-17 16:27 UTC, wslany commented
Thanks!