CATROID-1087 "Delete look" and "Delete background" do not work with looks from the web
Catrobat/Catroid pull request #4191
Opened 2021-05-20 11:54 UTC by Rawbat

Fixed the bug by adding the web look to the sprite look list.

https://jira.catrob.at/browse/CATROID-1087

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-30 10:22 UTC, adnaribo commented
The fix looks good, please just rebase :)

2021-06-30 20:37 UTC, adnaribo approved these changes

2021-07-02 15:34 UTC, blindguardian50 requested changes
Good work! Unfortunately there are a few problems:

By adding the web look to the look list the look is not fully removed from the project as long as the project is not exited completely. If the user decides to run the project again immediately, there are empty looks in the project which lead to unintended behavior. Please try to find a solution for that problem.

Also if the list is extended, you have to adapt the SetRelativeLookAction as now you would need to call 2 times the NextLookAction to get to the next look.

2021-08-15 10:04 UTC, blindguardian50 approved these changes

2021-08-15 10:05 UTC, merged