CATROID-1103 Refactor ProjectSaveTask to kotlin
Catrobat/Catroid pull request #4193
Opened 2021-05-23 21:29 UTC by blindguardian50

https://jira.catrob.at/browse/CATROID-1103

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-10 07:41 UTC, petbuer approved these changes

2021-06-13 10:30 UTC, gPathpp requested changes

2021-06-13 10:30 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectSaver.kt
> +fun saveLegoSettings(project: Project?, context: Context): Boolean {
Please rename to saveProjectSerial (or smth similar)

2021-06-13 10:30 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectSaver.kt
> +        project.settings.toTypedArray().filterIsInstance<LegoEV3Setting>().forEach { setting ->
Nice 👍

2021-06-13 10:30 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectSaver.kt
> +    fun saveProject() {
```suggestion
    fun saveProjectAsync(listener: ProjectSaveListener?) {
```
Please rename. Dependency injection of the listener is not necessary, but please do it if possible. (It also reduces the probability of bugs and memory leaks (If an activity is passed or some other context)
If you want you can get rid of the ProjectSaveListener with "onSaveProjectComplete: (Boolean) -> Unit"

It's also possible to dependency inject the scope:
```suggestion
    fun saveProject(scope: CoroutineScope, onSaveProjectComplete: (Boolean)->Unit) {
```
in the tests, you can then use runBlocking.

2021-06-24 15:19 UTC, gPathpp approved these changes
LGTM! 👍

2021-06-24 15:19 UTC, merged