CATROID-1070 REFACTOR ChangeTempoByAction to Kotlin
Catrobat/Catroid pull request #4203
Opened 2021-06-03 14:35 UTC by sahil9001

Refactoring of `ChangeTempoByAction` class to Kotlin

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-03 14:43 UTC, sahil9001 commented
Hello @wslany sir! I've made a PR regarding an issue can you please review it?

2021-06-09 23:13 UTC, frit96 requested changes
Please update the copyright year at the beginning of the file to 2021.
Also please add a new line at the end of the file so that jenkins can successfully run it's test.

2021-06-10 04:54 UTC, sahil9001 commented on catroid/src/main/java/org/catrobat/catroid/content/actions/ChangeTempoByAction.kt
> +            }
@frit96 I've made the requested changes, please have a look!

2021-06-10 11:28 UTC, frit96 approved these changes
Looks good now thanks

2021-06-30 17:08 UTC, Rawbat requested changes
Thanks! Have a look at the requested changes and also please squash your 3 commits into a single one.

2021-06-30 17:08 UTC, Rawbat commented on catroid/src/main/java/org/catrobat/catroid/content/actions/ChangeTempoByAction.kt
> +    private var scope: Scope? = null
The private keyword is not needed here, kotlin assumes it to be automatically private. Consider changing these two lines to:
lateinit var scope: Scope
lateinit var tempo: Formula
This way the variables do not have to be set nullable.

2021-06-30 17:08 UTC, Rawbat commented on catroid/src/main/java/org/catrobat/catroid/content/actions/ChangeTempoByAction.kt
> +    fun setTempo(tempo: Formula?) {
It is not necessary to explicitly declare setters in kotlin. Please remove them.

2021-07-06 13:23 UTC, frit96 requested changes
You again haven't added a newline at the end of your file so jenkins gets a warning.
Please always look if the jenkins testsytstem works and has no warnings left.

2021-07-28 16:54 UTC, Rawbat requested changes
There seems to be a lint warning. Please try if rebasing fixes this.

2021-08-20 07:56 UTC, sahil9001 commented
@wslany

2021-09-16 16:33 UTC, sahil9001 commented
@petbuer

2021-09-16 17:17 UTC, petbuer commented
Sorry that we missed this! @frit96 will re-review it soon.

2021-09-18 15:08 UTC, frit96 approved these changes
Looks good

2021-09-19 18:19 UTC, sahil9001 commented
@Rawbat

2021-09-30 12:13 UTC, Rawbat approved these changes
Sorry for the delay and thanks!

2021-09-30 12:15 UTC, merged