CATROID-1121 Refactor MainMenuActivity and related files to Kotlin
Catrobat/Catroid pull request #4209
Opened 2021-06-08 17:18 UTC by khushal1707

TIcket: https://jira.catrob.at/browse/CATROID-1121
- Added support for View Binding (As same as in https://github.com/Catrobat/Catroid/pull/4207 and also some other upgrade from the same)
- Refactored MainMenuActivity, TermsOfUseDialogFragment, AboutDialogFragment to kotlin
- Applied View Binding to above mentioned file

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-18 18:44 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +        termsOfUseUrlTextView.text = Html.fromHtml(termsOfUseUrl)
```suggestion
        termsOfUseUrlTextView.text = if (Build.VERSION.SDK_INT >= 24) {
            Html.fromHtml(termsOfUseUrl, HtmlCompat.FROM_HTML_MODE_LEGACY)
        } else {
            Html.fromHtml(termsOfUseUrl)
        }
```

2021-07-18 18:45 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +            .setPositiveButton(R.string.accept) { dialog: DialogInterface?, which: Int -> handleAgreedToPrivacyPolicyButton() }
```suggestion
.setNegativeButton(R.string.decline) { _, _ -> handleDeclinedPrivacyPolicyButton() }
.setPositiveButton(R.string.accept) { _, _ -> handleAgreedToPrivacyPolicyButton() }
```

2021-07-18 18:46 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +            .setOnKeyListener { dialog: DialogInterface?, keyCode: Int, event: KeyEvent? ->
```suggestion
            .setOnKeyListener { _, keyCode: Int, _ ->
```

2021-07-18 18:46 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +        linkTextView.text = Html.fromHtml(linkString)
```suggestion
        linkTextView.text = if (Build.VERSION.SDK_INT >= 24) {
            Html.fromHtml(linkString, HtmlCompat.FROM_HTML_MODE_LEGACY)
        } else {
            Html.fromHtml(linkString)
        }
```

2021-07-18 18:47 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +            .setPositiveButton(R.string.ok) { dialog: DialogInterface?, which: Int -> showTermsOfUseDialog() }
```suggestion
            .setPositiveButton(R.string.ok) { _, _ -> showTermsOfUseDialog() }
```

2021-07-18 18:47 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +            .setOnKeyListener { dialog: DialogInterface, keyCode: Int, event: KeyEvent? ->
```suggestion
           .setOnKeyListener { dialog: DialogInterface, keyCode: Int, _ ->
```

2021-07-18 18:52 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +            if (show) View.GONE else View.VISIBLE
```suggestion
       progressBarBinding.root.setVisibleOrGone(show)
       mainMenuBinding.fragmentContainer.setVisibleOrGone(!show)
```

2021-07-18 18:55 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/MainMenuActivity.kt
> +            ForegroundColorSpan(resources.getColor(R.color.beta_label_color)),
```suggestion
            ForegroundColorSpan(resources.getColor(R.color.beta_label_color, theme)),
```

2021-07-18 19:00 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/dialogs/TermsOfUseDialogFragment.kt
> +        termsOfUseUrlTextView.text = Html.fromHtml(termsOfUseUrl)
```suggestion
        termsOfUseUrlTextView.text = if (Build.VERSION.SDK_INT >= 24) {
            Html.fromHtml(termsOfUseUrl, HtmlCompat.FROM_HTML_MODE_LEGACY)
        } else {
            Html.fromHtml(termsOfUseUrl)
        }
```

2021-07-18 19:00 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/dialogs/TermsOfUseDialogFragment.kt
> +        termsOfUseDialogBuilder.setPositiveButton(R.string.ok) { dialog, id -> dialog.dismiss() }
```suggestion
        termsOfUseDialogBuilder.setPositiveButton(R.string.ok) { dialog, _ -> dialog.dismiss() }
```

2021-07-18 19:01 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/AboutDialogFragment.kt
> +        aboutCatrobatView.text = Html.fromHtml(aboutCatrobatUrl)
same

2021-07-18 19:01 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/dialog/AboutDialogFragment.kt
> +        developerUrlView.text = Html.fromHtml(developerUrl)
same

2021-07-18 19:17 UTC, ndrnour requested changes
please consider the suggested changes in your Code.

2021-07-18 19:42 UTC, ndrnour commented
also please fix this [APK FAILED](https://jenkins.catrob.at/job/Catroid/job/PR-4209/16/execution/node/39/log/)
`21:16:04  > Task :catroid:compileStandaloneDebugKotlin
21:16:04  e: /home/catroid/jenkins_slave/workspace/Catroid_PR-4209/catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.kt: (40, 49): Unresolved reference: surveyCampaign
21:16:04  e: /home/catroid/jenkins_slave/workspace/Catroid_PR-4209/catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.kt: (97, 9): Unresolved reference: surveyCampaign
21:16:04  e: /home/catroid/jenkins_slave/workspace/Catroid_PR-4209/catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.kt: (150, 13): Unresolved reference: surveyCampaign
21:16:04  e: /home/catroid/jenkins_slave/workspace/Catroid_PR-4209/catroid/src/main/java/org/catrobat/catroid/ui/BaseActivity.kt: (151, 13): Unresolved reference: surveyCampaign
21:16:04  
21:16:04  > Task :catroid:compileStandaloneDebugKotlin FAILED`

2021-07-21 03:22 UTC, khushal1707 commented
Done!

2021-08-01 13:14 UTC, ndrnour commented
please keep an eye on #4286, once it gets merged, rebase and then I'll review it

2022-05-27 12:52 UTC, bengaal approved these changes
Looks good to me!

2022-08-02 14:39 UTC, DinosaurierRex approved these changes
PO review LGTM 👍 

@Walcho1125 or @juliajulie95 Please merge! Thnks

2022-08-02 14:40 UTC, merged