CATROID-1067 REFACTOR ActionPhysicsFactory to Kotlin
Catrobat/Catroid pull request #4210
Opened 2021-06-08 20:27 UTC by frit96

https://jira.catrob.at/browse/CATROID-1067
Refacrotring of ActionPhysicsFactory to Kotlin

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-10 15:06 UTC, adnaribo requested changes

2021-06-10 15:06 UTC, adnaribo commented on catroid/src/main/java/org/catrobat/catroid/physics/content/ActionPhysicsFactory.kt
> +    // PHYSICS
Please just delete all comments in the file

2021-07-01 16:59 UTC, blindguardian50 requested changes
Good Work! Please consider my suggested change!

2021-07-01 16:59 UTC, blindguardian50 commented on catroid/src/main/java/org/catrobat/catroid/physics/content/ActionPhysicsFactory.kt
> +    private fun getPhysicsObject(sprite: Sprite): PhysicsObject = physicsWorld.getPhysicsObject(sprite)
Please move this function below the physicsWorld member.

2021-07-05 09:27 UTC, blindguardian50 approved these changes
Looks good to me!

2021-07-05 19:54 UTC, adnaribo approved these changes
Looks good :+1:

2021-07-06 13:16 UTC, merged