CATROID-1099 REFACTOR ProjectCopyTask to Kotlin
Catrobat/Catroid pull request #4211
Opened 2021-06-08 22:00 UTC by frit96

https://jira.catrob.at/browse/CATROID-1099
Refactoring of ProjectCopyTask to Kotlin

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-23 20:03 UTC, adnaribo requested changes
Please replace AsyncTask with Coroutines. More infos are in the ticket description under point 3 :)

2021-08-05 10:37 UTC, hofcle78 requested changes

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
> +		ProjectCopyTask.ProjectCopyListener{
```suggestion
{
```

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.java
> +			new ProjectCopyTask(projectData.getDirectory(), name, this).taskAsync();
```suggestion
			ProjectCopyTask projectCopyTask = new ProjectCopyTask(projectData.getDirectory(), name);
			projectCopyTask.taskAsync(success -> {
				onCopyProjectComplete(success);
				return Unit.INSTANCE;
			});
```

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectCopyTask.kt
> +            )
```suggestion
            Log.e(TAG, "Something went wrong while copying " + sourceDir.absolutePath + " to " + destinationName, e)
```

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectCopyTask.kt
> +
```suggestion
```

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectCopyTask.kt
> +    private var weakListenerReference: WeakReference<ProjectCopyListener>? = null
```suggestion
    private val destinationName: String
) {
```

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectCopyTask.kt
> +        scope: CoroutineScope = CoroutineScope(Dispatchers.IO),
```suggestion
        onCopyProjectComplete: (Boolean) -> Unit = {},
        scope: CoroutineScope = CoroutineScope(Dispatchers.IO),
```

2021-08-05 10:37 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/io/asynctask/ProjectCopyTask.kt
> +                taskComplete(success)
```suggestion
                onCopyProjectComplete(success)
```

2021-08-06 06:38 UTC, hofcle78 approved these changes
Looks Good!

2021-08-06 15:23 UTC, petbuer requested changes
Thanks a lot!
Please also refactor the corresponding test (CopyProjectTest.java) to Kotlin.

2021-08-19 09:42 UTC, hofcle78 requested changes

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +import androidx.test.core.app.ApplicationProvider
```suggestion
import androidx.test.platform.app.InstrumentationRegistry.getInstrumentation
import androidx.test.core.app.ApplicationProvider.getApplicationContext
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +        )
```suggestion
        openActionBarOverflowOrOptionsMenu(getInstrumentation().targetContext)
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +        )
```suggestion
        val project = Project(getApplicationContext(), projectName)
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +                .resources,
```suggestion
            getInstrumentation().context.resources,
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +            ),
```suggestion
            File(project.defaultScene.directory, Constants.SOUND_DIRECTORY_NAME),
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +        )
```suggestion
        saveProjectSerial(project, getApplicationContext())
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +        )
```suggestion
        val backgroundSprite = Sprite(getApplicationContext<Context>().getString(R.string.background))
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +                .resources,
```suggestion
            getInstrumentation().context.resources,
```

2021-08-19 09:42 UTC, hofcle78 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/ProjectCopierTest.kt
> +            "catroid_sunglasses.png", 1.0
```suggestion
            File(project.defaultScene.directory, Constants.IMAGE_DIRECTORY_NAME),
            "catroid_sunglasses.png",
            1.0
```

2021-08-19 13:15 UTC, frit96 commented
I made all the requested changes

2021-08-22 13:26 UTC, hofcle78 approved these changes

2021-08-24 08:20 UTC, petbuer approved these changes
Thanks!

2021-08-24 18:13 UTC, adnaribo approved these changes

2021-08-25 14:44 UTC, merged