CATROID-1129 Fade particle effect in/out brick
Catrobat/Catroid pull request #4216
Opened 2021-06-12 10:27 UTC by devsebastian

Ticket: https://jira.catrob.at/browse/CATROID-1129

### Introduce Particle Effects in Catrobat
* added the new ParticleEffectsFade Brick which has 2 options to fade in or to fade out.
* the particle effects scale will depend on the size of the look, so the bigger the look bigger the "flame"
* particle default color: red 
* A new particle file will take care of all the default properties of the particle effects so as to not overwhelm the user with many options, some of these properties could now be controlled using custom bricks that will be added later...
* Added a test to check whether the boolean property of the particle effect is switched on or off on the sprite on adding the fade In or fade out brick, please let me know if any further tests are required to be added?
<img src="https://user-images.githubusercontent.com/19506171/121772907-19019880-cb96-11eb-9e6c-bf76d4162850.gif" width="40%"/>

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-14 10:21 UTC, Rawbat commented
Please also include entries for this brick in the files BricksHelpUrlTest.java and RtlBrickTest.java

2021-06-14 10:53 UTC, Rawbat commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.java
> +	Script script;
Please declare this as private

2021-06-14 10:57 UTC, Rawbat commented on catroid/src/main/java/org/catrobat/catroid/content/actions/FadeParticleEffectAction.java
> +	Sprite sprite;
Please declare this as private

2021-06-14 11:00 UTC, Rawbat requested changes
Please change the copyright to 2021 in all edited files.

2021-06-16 19:22 UTC, devsebastian commented
Done 👍 and thank you so much @Rawbat for helping me fix the failing tests in Jenkins!!

2021-06-17 10:04 UTC, Rawbat approved these changes
Great, Thanks!

2021-06-19 05:54 UTC, wslany requested changes
Wow, awesome!!

What I observed and hope you can change or fix:
- The particle effects continue to move in the pause menu (when exiting the stage, see screenshot). Instead, it should be frozen (but continue again if the resume button is tapped in the pause menu). Please add a test. 
![image](https://user-images.githubusercontent.com/1747888/122631112-5bacfe80-d0c9-11eb-8c0c-3a051a994497.png)
- Please move the new brick in the green Looks category upwards, between "Change color by" and "Clear graphics effects"
- The "Clear graphics effects" shall immediately cancel the particle effect for the object (no fading out; also, if the object has clones, only the one clone or original executing the "Clear graphics effect" brick should cancel its particle effect). Please add a test. 
- If an object has a "Fade in particle effect" brick in any of its scripts, and that brick has been executed at least once successfully in the current session for this project, then, even if it is never executed later (e.g., if it has been commented out, or there is another reason why it is not immediately executed, e.g., because of a "Wait 100 seconds" brick), the particle effect is _immediately_ shown when the scene starts, and all waits or other bricks before it are ignored for the particle effect. Exiting the current project and reentering resets this, and the particle effect is again correctly shown only when the Fade in brick is executed. Please add tests. 
- There is no fading out, the particle effect incorrectly stops abruptly. Instead, the fading out should also take some time, like the fading in. Please add a test (also for the fading in). Note: Later we can add parameters for it that all ow to specify the amount of time, but not for this first version.
- Please rename the brick to "Fade <in/out> particle effect", i.e., the pull down should be after the first word in English. Can this be done with a parameter field in the string resource so that the  positions of the words are flexible for translations? Reason: The ordering of words in Japanese grammar for instance is often reversed compared to English, and if it is just one string resource, it is much clearer for translators in that way. I have tried to suggest a possible format in my in-lined comment.
- If there is no background look, or there is a white background look, or if there is another object (i.e., different from the background) _behind_ the object, and that second object's look covers the complete stage in white below the first object (the one with the particle effect), then the particles of a foreground object are not visible. Note that this is quite strange, because when the background's look is, e.g., completely black, then the particles have a nice red color. Why are they white if the underground is white or transparent? Instead, the particles should be visible in these cases. Please also add a test. Note that this is _not_ necessary if the look _below_ the object, either from the background or from a second object's look that covers the complete stage has the same color as the particles (i.e., red).  
- The color of the particles seem to depend on the background color. How is the color decided? Note: Later we should add other parameters that allow to set the color, size, and length of the particles. But that should be done in later, separate tickets.
- I haven't checked yet everything regarding layers, clones, and starting or resuming scenes. Is it all working fine? If so, please add corresponding test cases.
- The particle effect by default always seems to point upwards unless the object moves. Changing the gravity vector does not influence the particles' direction. Instead, the direction unless the object is moving shall point in the opposite direction of the gravity vector. Also, please make sure that it works correctly in landscape mode. Please also add tests.

2021-06-20 09:07 UTC, devsebastian commented
To your questions how is the color decided, and why the particle effect is not visible in lighter backgrounds: 

By default the particle have the "additive" property set to true, this gives a realistic look to the effect, where the core is lighter than, the outer regions of the flame which gradually become darker like shown in the image:

![Screenshot (191)](https://user-images.githubusercontent.com/19506171/122668116-3953d780-d1d4-11eb-8aaa-9e338eaa2100.png)

This is in contrast to when we set the additive property to false, this makes the entire effect completely opaque rendering an unrealistic and uniformly colored effect as shown in the below image:

![Screenshot (192)](https://user-images.githubusercontent.com/19506171/122668117-3a850480-d1d4-11eb-8711-c91df32463a1.png)

although the additive effect looks more interesting, but it won't be visible in lighter backgrounds.

![Screenshot (193)](https://user-images.githubusercontent.com/19506171/122668119-3b1d9b00-d1d4-11eb-9dee-6be4332030d0.png)

of course we can always set the additive property to false, to make the effect visible on all backgrounds.

![Screenshot (194)](https://user-images.githubusercontent.com/19506171/122668120-3b1d9b00-d1d4-11eb-9e5e-9f8995fdfa3d.png)

Though I thought, we could add this property with the fade particle effect brick in a later ticket, so that the user can toggle the property anytime and the final control lie with the user, please let me know what you think?

2021-06-20 10:28 UTC, wslany commented
One idea: 
1. Since the empty background is the default for new projects, i.e., exactly where users might want to explore the particle effects, what we could do is the following: as a special case (and only in that case) the "additive" property shall be turned off at the beginning if and only if there is no background look. 
2. Immediately add a feature (a separate brick?) that allows to turn off and on this "additive property". This then also allows to explicitly override the default defined in the step 1 above. 

What do you think? Note that we already have several such special cases to make things easier and more intuitive for users.

2021-06-21 17:15 UTC, devsebastian commented
Changes:
1. particle gravity is directly equal to scene gravity.
2. fade out brick now has a gradual fade-out effect
3. ClearGraphicsBrick stops the particle effect without any fade effect
4. additive property has been added to the fadeParticlebrick itself. the user can now switch the additive effect on or off, and correspondingly the particle visibility and fade color.
5. the particle effects work on all sprites and clones (particle effect on clones behaves exactly the same way as on any other sprite).
6. the particles pause on their positions and resume back on pressing the pause and resume button respectively!
7. added tests for most of the use cases including stage pause, stage resume, add clone and add fade particle effect on the clone, check whether the additive property is enabled or disabled, etc.

2021-06-22 00:30 UTC, wslany commented
Thanks.
1. Please write "particle" with a small letter in the bricks and remove the ":" before the spinner parameters.
2. Please make two bricks out of it. Reason: the additive parameter makes no sense when the first spinner for in and out is set to "out". 
3. The second brick should be "Turn the particle effect's additivity on/off" (with a spinner for on and off, default is off). Note: can this be set for the object that executes the brick only, or does it have to be global for all objects? Both are OK, but the first would be preferable. 
4. Please set the additivity automatically to "off" whenever the background is empty (either no background look, or the background's look is hidden). As soon as a background look is visible, revert the additivity to its earlier value, before there was no background.

2021-06-22 01:09 UTC, wslany commented
6. Please make the bricks' texts parameterized so that the spinners can be anywhere in the text, and the translators can decide whether there is a front and/or rear part before and/or after the spinner. It is ok that the spinner is in its own line.

2021-06-22 02:01 UTC, wslany commented
7. The bug is still present that the particle effect is immediately visible after a _**re**_-start of the stage (without first leaving the project by returning to Catroid's main menu) or a resume from the stage's pause menu, even if the scripts of the object actually turn it on only a few seconds after the start of the scene, and even if the scripts have been edited by the user since executing the project earlier. It works fine at the first time after entering the project. Please, as always, _**first**_ add a test for the corrected behavior, then correct it.

2021-06-22 02:04 UTC, wslany commented
> 6. the particles pause on their positions and resume back on pressing the pause and resume button respectively!

This didn't work when I just tried it out.

2021-06-24 06:07 UTC, wslany approved these changes

2021-06-24 06:10 UTC, wslany commented on catroid/src/main/java/org/catrobat/catroid/common/Constants.java
> +	public static final double CURRENT_CATROBAT_LANGUAGE_VERSION = 1.05;
Please rebase and further increase compared to the develop branch.

2021-06-24 10:46 UTC, Rawbat approved these changes
Looks good, thanks!

2021-06-28 15:41 UTC, ndrnour requested changes
please fix the warnings too.

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +            StorageOperations.deleteDir(File(FlavoredConstants.DEFAULT_ROOT_DIRECTORY, projectName))
no need for that, the test rule will take care of that for you.
for more info see `BaseActivityTestRule.java`

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/FadeParticleEffectBrick.kt
> +        private const val FADE_OUT = 1
please make them public (just remove private access modifier). and use them in the test instead of 0 and 1.

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(1))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/content/brick/stage/ParticleEffectsTest.kt
> +        script.addBrick(FadeParticleEffectBrick(0))
@here

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/FadeParticleEffectBrick.kt
> +        private const val FADE_OUT = 1
see @here annotations

2021-06-28 15:41 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/FadeParticleEffectBrick.kt
> +    private var fadeSpinnerSelectionId: Int
```suggestion
    private var fadeSpinnerSelectionId: Int = FADE_IN
```
and please remove the constructor at line 44

2021-07-09 11:37 UTC, wslany requested changes
Thanks a lot!! Please change tests as suggested.

Please also add two tests for the scene transition bricks (Start scene and Continue scene), as follows:
In both tests, there is one object in "Scene 1" with the following script, as well as a second scene "Scene 2" that, in the **particleEffectAfterSceneRestartsTest** test only executes a "Start Scene 1" brick when the scene starts (e.g., via a brick in the Background), and in the **particleEffectAfterSceneContinuesTest** test only executes a "Continue Scene 1" brick when the scene starts.

The script of the object in Scene 1 in both tests is the following:
```
When scene starts
Wait 0.2 seconds
Fade particle effect in
Start Scene 1
```

In case of **particleEffectAfterSceneRestartsTest**, the test part should then be:
```
        onView(ViewMatchers.withId(R.id.button_play)).perform(click())
        onView(ViewMatchers.isRoot()).perform(wait(300))
        assertFalse(projectManager.currentSprite.look.hasParticleEffect)
        onView(ViewMatchers.isRoot()).perform(wait(300))
        assertTrue(projectManager.currentSprite.look.hasParticleEffect)
```

In case of **particleEffectAfterSceneContinuesTest**, the test part should then be:
```
        onView(ViewMatchers.withId(R.id.button_play)).perform(click())
        onView(ViewMatchers.isRoot()).perform(wait(300))
        assertTrue(projectManager.currentSprite.look.hasParticleEffect)
```

2021-08-10 09:04 UTC, wslany approved these changes

2021-08-10 09:17 UTC, ndrnour approved these changes

2021-08-10 09:20 UTC, merged