CATROID-1131 Refactor BrickCategoryAdapter and Fragment
Catrobat/Catroid pull request #4217
Opened 2021-06-13 09:56 UTC by Walcho1125

*Please enter a short description of your pull request and add a reference to the Jira ticket.*
https://jira.catrob.at/browse/CATROID-1131
Refactor BrickCategoryAdapter and BrickCategoryAdapter to Kotlin

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-22 16:32 UTC, dandrawes approved these changes
Well done!

2021-07-02 17:14 UTC, gPathpp requested changes

2021-07-02 17:14 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.kt
> +    }
```suggestion

```

2021-07-02 17:14 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/BrickCategoryFragment.kt
> +        setHasOptionsMenu(true)
```suggestion
        setHasOptionsMenu(false)
```
Please check if this works, the other solution is a bit odd.

2021-07-04 18:19 UTC, gPathpp approved these changes
As discussed, the main refactoring/implementation happens in another (GSoC) ticket.

2021-07-04 18:23 UTC, merged