CATROID-677 Make "No internet" message easier to read
Catrobat/Catroid pull request #4224
Opened 2021-06-17 14:11 UTC by frit96

https://jira.catrob.at/browse/CATROID-677
Make "No internet" message easier to read

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-07 20:37 UTC, adnaribo requested changes
Unfortunately the same happens as in https://github.com/Catrobat/Catroid/pull/3739 See screenshot below
![Screenshot from 2021-07-07 22-30-11](https://user-images.githubusercontent.com/48415989/124825433-e750d700-df73-11eb-90e7-ba387c564461.png)

2021-08-13 10:06 UTC, hofcle78 requested changes

2021-08-13 10:06 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
> +					|| errorCode == ERROR_UNKNOWN) {
```suggestion
					|| errorCode == ERROR_UNKNOWN),
					|| errorCode == ERROR_PROXY_AUTHENTICATION) {
```
adding **ERROR_PROXY_AUTHENTICATION** should fix the problem which occurs on BrowserStack devices.
with this changes i have tested it on:
- Galaxy S9 Android 10 (real device)
- Pixel 4 Android 11 (Android Studio)
- Pixel 3 Android 9 (BrowserStack)
- GalaxyTab S5e (BrowserStack)
![image](https://user-images.githubusercontent.com/42325361/129341101-058608cb-d47d-4da5-bb25-394bddf76545.png)

2021-08-13 10:06 UTC, hofcle78 commented on catroid/src/main/java/org/catrobat/catroid/ui/WebViewActivity.java
> +				Log.e(TAG, "could'nt connect to the server! info: " + description + " : " + errorCode);
```suggestion
				Log.e(TAG, "couldn't connect to the server! info: " + description + " : " + errorCode);
```

2021-08-14 15:14 UTC, frit96 commented
Thank you for the review I made all the requested changes

2021-08-16 07:06 UTC, hofcle78 approved these changes

2021-08-21 17:04 UTC, merged

2021-08-21 17:04 UTC, wslany commented
Thanks!