CATROID-1123 Refactor ProjectUploadActivity and Controller to Kotlin
Catrobat/Catroid pull request #4226
Opened 2021-06-18 12:19 UTC by khushal1707

Ticket: https://jira.catrob.at/browse/CATROID-1123

Refactored files:
- ProjectUploadActivity
- ProjectUploadController

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-08-11 16:14 UTC, Walcho1125 approved these changes
Looks good to me!

2021-08-17 09:34 UTC, gPathpp requested changes

2021-08-17 09:34 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/controller/ProjectUploadController.kt
> +        return intent
```suggestion
        return intent.apply {
           putExtra(Constants.EXTRA_RESULT_RECEIVER, resultReceiverWrapper)
           ...
        }
```

2021-08-20 09:50 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/ProjectUploadActivity.kt
> +        if (uploadProgressDialog?.isShowing == true) {
Sorry, I didn't see that this Boolean can be null. So it's fine :+1:

2021-09-01 07:20 UTC, gPathpp approved these changes
LGTM

2021-09-01 07:20 UTC, merged