CATROID-1035 FileNotFoundException when duplicate delete look in clone
Catrobat/Catroid pull request #4240
Opened 2021-06-25 11:30 UTC by qlin93

https://jira.catrob.at/browse/CATROID-1035

Deleting a look in a clone now only removes the look from the lookslist of the clone and doesn't delete the lookfile. 
When a look is deleted in an original sprite the look is also removed from the looklist and the lookfile is flagged and is deleted when the Stage lifecycle ends. 

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-25 13:02 UTC, petbuer approved these changes

2021-07-08 09:23 UTC, gPathpp requested changes

2021-07-08 09:23 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
> +			deleteLookFilesToBeDeleted();
This makes me think, is there a test that guarantees that the look was deleted? :thinking: 
If not please add one (Unit Test)

2021-07-08 09:23 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/content/actions/DeleteLookAction.kt
>              xstreamSerializer.saveProject(ProjectManager.getInstance().currentProject)
Please, check if this line is still necessary here :)

2021-07-08 09:23 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/stage/StageLifeCycleController.java
> +	}
Please, move this method and the file-set to a companion object in the respective Action.
```suggestion
```

2021-07-08 09:24 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/content/actions/DeleteLookAction.kt
>              xstreamSerializer.saveProject(ProjectManager.getInstance().currentProject)
xstreamSerializer.saveProject

2021-07-17 11:53 UTC, qlin93 commented
Thanks for the review @gPathpp! As we talked about on Slack the handling for the deletion is now changed, so that unused Look files are deleted when a project is loaded instead of when the Stage is destroyed. There is also a new instrumented unit test to test this behaviour.

2021-07-23 10:27 UTC, gPathpp requested changes
Nice implementation.
Please have a look at https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/ and improve the test.
@wslany, please have a look at it to check if it suits your requirements.

2021-07-23 10:27 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/io/LookFileGarbageCollector.kt
> +object LookFileGarbageCollector {
Please make cleanUpUnusedLookFiles thread-safe ;)

2021-07-23 10:27 UTC, gPathpp commented on catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/DeleteLookActionFileCleanupTest.kt
> +        XstreamSerializer.getInstance().saveProject(project)
Since we don't have to test if StorageOperations.deleteFile(file) really deletes a file,
consider Mockito to test your implementation :)

2021-07-23 10:27 UTC, gPathpp commented on catroid/src/androidTest/java/org/catrobat/catroid/test/content/actions/DeleteLookActionFileCleanupTest.kt
> +    }
Please consider using a parameterized Test and add more examples :)

2021-08-07 12:11 UTC, Rawbat approved these changes
Great, thanks!

2021-08-07 12:15 UTC, merged