CATROID-1139 Refactor controller and finder of ScriptFragment to kotlin
Catrobat/Catroid pull request #4243
Opened 2021-06-27 14:56 UTC by khushal1707

Ticket: https://jira.catrob.at/browse/CATROID-1139
- Refactored ScriptController and ScriptFinder to kotlin
- Applied view-binding in ScriptFinder

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-10 14:27 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +            if (ProjectManager.getInstance().currentProject.isCastProject &&
please use injected projectManager instead.

2021-07-10 14:28 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +            return ProjectManager.getInstance().currentProject.broadcastMessageContainer.addBroadcastMessage(
same.

2021-07-10 14:28 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +                ProjectManager.getInstance().currentProject.isCastProject && CastManager.unsupportedBricks.contains(
same.

2021-07-11 12:33 UTC, khushal1707 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +            if (ProjectManager.getInstance().currentProject.isCastProject &&
Done!

2021-07-11 12:33 UTC, khushal1707 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +            return ProjectManager.getInstance().currentProject.broadcastMessageContainer.addBroadcastMessage(
done

2021-07-11 12:33 UTC, khushal1707 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +                ProjectManager.getInstance().currentProject.isCastProject && CastManager.unsupportedBricks.contains(
Done

2021-08-01 15:49 UTC, ndrnour commented
the search script feature seems not to work anymore. please fix it. see attached screen recording.

2021-08-01 15:49 UTC, ndrnour commented
https://user-images.githubusercontent.com/18437036/127777176-b375913f-6828-4262-81e5-e43b7ea98207.mp4

2021-08-01 15:51 UTC, ndrnour requested changes
the search script feature seems not to work anymore. please fix it. see attached screen recording.

2021-08-03 03:30 UTC, khushal1707 commented
> the search script feature seems not to work anymore. please fix it. see attached screen recording.

Fixed it! Working fine now.

2021-08-05 12:45 UTC, ndrnour approved these changes

2021-08-17 08:38 UTC, gPathpp requested changes
https://medium.com/swlh/12-steps-to-convert-your-java-class-to-kotlin-the-right-way-9a718cfb498d

Have a close look at steps 4, 7, 8 and 12, please.

2021-08-17 08:38 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/ScriptFinder.kt
> +        fun searchBrickViews(v: View?, searchQuery: String?): Boolean {
Please, simplify this.

2021-08-17 08:38 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/ScriptFinder.kt
> +            searchResultIndex = (searchResultIndex + 1) % searchResults!!.size
No `!!`

2021-08-17 08:38 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/ScriptFinder.kt
> +    @Suppress("ComplexMethod")
Please, clean the code.

2021-08-17 08:38 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +                    brick.look = lookController.packForSprite(brick.look, destinationSprite)
```suggestion
            when(brick) {
                is SetLookBrick, is WhenBackgroundChangesBrick ->
                    brick.look = brick.look?.let{lookController.packForSprite(it, destinationSprite)}
```
https://kotlinlang.org/docs/control-flow.html#when-expression
Improve all others too, please.

2021-08-17 09:32 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/controller/ScriptController.kt
> +            for (brick in bricksToPack) {
Use for each, please

2021-09-01 07:32 UTC, merged