CATROID-1142 Refactor SoundListFragment and related files to kotlin
Catrobat/Catroid pull request #4256
Opened 2021-07-09 07:08 UTC by khushal1707

https://jira.catrob.at/browse/CATROID-1142

Refactored files:
- SoundListFragment
- SoundController
- SoundAdapter

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-11 10:36 UTC, Walcho1125 requested changes
Well done! pls take a look at the remarks

2021-07-11 10:36 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
> +        SnackbarUtil.showHintSnackbar(activity, R.string.hint_sounds)
```suggestion
        SnackbarUtil.showHintSnackbar(requireActivity(), R.string.hint_sounds)
```

2021-07-11 10:36 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
> +                activity, resources.getQuantityString(
```suggestion
                requireContext(), resources.getQuantityString(
```

2021-07-11 10:36 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
> +        val intent = Intent(activity, BackpackActivity::class.java)
```suggestion
        val intent = Intent(requireContext(), BackpackActivity::class.java)
```

2021-07-11 10:36 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
> +                activity, resources.getQuantityString(
```suggestion
                requireContext(), resources.getQuantityString(
```

2021-07-11 10:36 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
> +            val intent = Intent(activity, PocketMusicActivity::class.java)
```suggestion
            val intent = Intent(requireContext(), PocketMusicActivity::class.java)
```

2021-07-11 10:36 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/SoundListFragment.kt
> +            activity, resources.getQuantityString(
```suggestion
            requireContext(), resources.getQuantityString(
```

2021-07-11 12:55 UTC, khushal1707 commented
Done!

2021-07-11 14:30 UTC, Walcho1125 approved these changes
Looks good to me now, well done!

2021-07-11 17:38 UTC, ndrnour commented
Generating the APKs is failing for some reason? please check [that.](https://jenkins.catrob.at/job/Catroid/job/PR-4256/)

2021-07-12 05:14 UTC, khushal1707 commented
Surprisingly, the error got resolved without any changes!

2021-08-01 16:09 UTC, ndrnour requested changes
please watch the attached screen recording and fix the bug related to the displayed image holder.

2021-08-01 16:11 UTC, ndrnour commented
https://user-images.githubusercontent.com/18437036/127777860-6595316a-2625-4c5f-9ec5-7dfd4c6bc5f7.mp4

2021-08-03 02:12 UTC, khushal1707 commented
> please watch the attached screen recording and fix the bug related to the displayed image holder.

Few doubts regarding this issue:

- This bug also present in develop, please verify.
- If it's present in develop, do we need to create a ticket for it?
- Do we play 2 or more sound simultaneously in sound list?

2021-08-05 11:08 UTC, ndrnour commented
> > please watch the attached screen recording and fix the bug related to the displayed image holder.
> 
> Few doubts regarding this issue:
> 
> * This bug also present in develop, please verify.
> * If it's present in develop, do we need to create a ticket for it?
> * Do we play 2 or more sound simultaneously in sound list?

no need for a ticket, please fix it and mention that in the commit message.
only one sound can be played. 
if you need help with that, let me know.

2021-08-12 20:37 UTC, ndrnour approved these changes

2021-08-12 20:37 UTC, ndrnour commented
nice thanks for the extra bug fix

2021-08-22 14:29 UTC, merged