CATROID-1176 Added test for creating project and afterwards checking …
Catrobat/Catroid pull request #4268
Opened 2021-07-21 17:00 UTC by dorianpercic

…if avaliable on device

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-25 17:05 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CreateProjectTest.kt
> +        var newProjectName = "newProjectTest"
```suggestion
        val newProjectName = "newProjectTest"
```

2021-07-25 17:06 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CreateProjectTest.kt
> +            .perform(ViewActions.replaceText(newProjectName))
```suggestion
        onView(allOf(withId(R.id.input_edit_text), isDisplayed(), instanceOf(EditText::class.java)))
            .perform(ViewActions.replaceText(newProjectName))
```

2021-07-25 17:10 UTC, ndrnour requested changes
please fix the warnings and consider my suggestions

2021-07-25 17:11 UTC, ndrnour commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/fragment/CreateProjectTest.kt
> +        TestUtils.deleteProjects(javaClass.simpleName)
this line is not needed, the BaseActivityTestRule will take care of that.
```suggestion
        
```

2021-07-26 08:45 UTC, dorianpercic commented
> please fix the warnings and consider my suggestions

I committed your suggestions!

2021-07-27 14:05 UTC, closed without merging