CATROID-1118: [GSOC21] Refactor ProjectListActivity and its related fragments to kotlin
Catrobat/Catroid pull request #4276
Opened 2021-07-25 19:30 UTC by ndrnour

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-08-12 09:53 UTC, Walcho1125 requested changes
Please take a look at the remarks, try to avoid using companion objects just for class intern locally used constants like in ProjectActivity.kt etc. as the overhead for companion objects are higher than just declaring them as file-private constants.

2021-08-12 21:11 UTC, ndrnour commented on catroid/src/main/java/org/catrobat/catroid/ui/ProjectActivity.kt
> +        const val EXTRA_FRAGMENT_POSITION = "fragmentPosition"
fixed

2021-08-13 19:16 UTC, ndrnour commented
rebased and fixed the merge conflicts and got rid of companion objects.

2021-08-21 11:10 UTC, Walcho1125 approved these changes
Looks good to me!

2021-12-25 19:40 UTC, closed without merging