CATROID-1093 REFACTOR ListProjectFilesTask to Kotlin
Catrobat/Catroid pull request #4284
Opened 2021-07-29 07:55 UTC by hofcle78

https://jira.catrob.at/browse/CATROID-1093

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-08-05 14:24 UTC, frit96 reviewed
Overall it looks very good just add the small changes I requested.

2021-08-05 14:24 UTC, frit96 commented on catroid/src/main/java/org/catrobat/catroid/ui/filepicker/FilePickerActivity.kt
> +                ProjectFileLister(this@FilePickerActivity).listProjectFilesAsync(getStorageRoots())
```suggestion
                ProjectFileLister().listProjectFilesAsync(getStorageRoots(), this@FilePickerActivity)
```

2021-08-06 15:53 UTC, frit96 commented
Thanks looks good now!

2021-08-25 14:09 UTC, petbuer requested changes
Please have a look at my comments.

2021-08-25 15:36 UTC, frit96 approved these changes

2021-11-23 10:39 UTC, frit96 commented
@hofcle78 please resolve the conflicts and rebase

2021-11-24 07:47 UTC, hofcle78 commented
Done. :+1:

2022-10-30 21:45 UTC, reichli commented
closed due to inactivity

2022-10-30 21:45 UTC, closed without merging