CATROID-1169 Refactored AddUserDataToUserDefinedBrickFragment from ja…
Catrobat/Catroid pull request #4324
Opened 2021-08-24 20:14 UTC by dorianpercic

…va to kotlin.

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-09-27 10:34 UTC, ChriMoser commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.kt
> +            val fragmentManager = fragmentManager
In the old file the keyboard was hidden at this position, why not here aswell?

2021-09-27 10:41 UTC, ChriMoser requested changes
Looks good, but some minor changes/questions to resolve.

Please also fix the Static Analysis warnings from Jenkins!

2021-09-27 10:41 UTC, ChriMoser commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDefinedBrickFragment.kt
> +            if (brickIsEmpty == true) {
is "== true" needed?

2021-09-27 10:41 UTC, ChriMoser commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDefinedBrickFragment.kt
> +                if (brickIsEmpty == true) {
is "== true" needed?

2021-09-27 10:41 UTC, ChriMoser commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.kt
> +            val fragmentManager = fragmentManager
In the old file the keyboard was hidden at this position, why not here aswell?

2022-01-24 15:47 UTC, Walcho1125 requested changes
Please look at the remarks as the app crashes because of an off-by-one error and update the copyright line in every file

2022-01-24 15:47 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDefinedBrickFragment.kt
> +        }
This also causes 
```
AndroidRuntime: FATAL EXCEPTION: main
    Process: org.catrobat.catroid, PID: 17448
    java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
        at java.util.ArrayList.get(ArrayList.java:437)
        at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
        at org.catrobat.catroid.ui.fragment.AddUserDefinedBrickFragment.onPrepareOptionsMenu(AddUserDefinedBrickFragment.kt:121)
        at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2820)
        at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:2703)
        at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:399)
        at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3097)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:523)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:457)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
```suggestion
        for (index in 0 until menu.size()) {
            menu.getItem(index).isVisible = false
        }
```

2022-01-24 15:47 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.kt
> +        }
This results in:
```
AndroidRuntime: FATAL EXCEPTION: main
    Process: org.catrobat.catroid, PID: 17448
    java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
        at java.util.ArrayList.get(ArrayList.java:437)
        at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
        at org.catrobat.catroid.ui.fragment.AddUserDefinedBrickFragment.onPrepareOptionsMenu(AddUserDefinedBrickFragment.kt:121)
        at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2820)
        at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:2703)
        at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:399)
        at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3097)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:523)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:457)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
caused by an off-by-one error, instead use:
```suggestion
        for (index in 0 until menu.size()) {
            menu.getItem(index).isVisible = false
        }
```

2022-01-24 15:47 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDataToUserDefinedBrickFragment.kt
> + * Copyright (C) 2010-2021 The Catrobat Team
please update in every file
```suggestion
 * Copyright (C) 2010-2022 The Catrobat Team
```

2022-01-24 15:47 UTC, Walcho1125 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/AddUserDefinedBrickFragment.kt
> + * Copyright (C) 2010-2021 The Catrobat Team
```suggestion
 * Copyright (C) 2010-2022 The Catrobat Team
```

2022-03-30 13:11 UTC, Walcho1125 approved these changes
Thanks!

2022-03-30 13:11 UTC, merged