CATROID-1105 Scoped storage-external storage files
Catrobat/Catroid pull request #4351
Opened 2021-10-09 09:45 UTC by csum1

To support scoped storage the system file picker is used for:
- import/export projects
- read/write variable to file bricks
- write embroidery to file

Depending on API version the old mechanism is used for <API29

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-11-01 14:45 UTC, juliajulie95 requested changes

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +                    override fun afterTextChanged(s: Editable) {
rename variable

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +                            val error = validateInput(s.toString(), getContext())
context

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +                    val chip = Chip(getContext())
context

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +    @Suppress("UNUSED_PARAMETER")
delete

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +    @Suppress("UNUSED_PARAMETER")
delete

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
> +        } catch (e: IOException) {
exception

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
> +                } catch (e: IOException) {
exception

2021-11-01 14:45 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/ProjectListFragment.kt
> +                    Log.e(TAG, "Well, that's awkward.", e)
could not parse local project

2021-11-01 15:01 UTC, csum1 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +                            val error = validateInput(s.toString(), getContext())
an dieser Stelle ist "context" zweideutig, mit getContext() ist es explizit der Context vom Fragment. "context" würde sich auf InputWatcher.context beziehen. Außerhalb von diesem Scope ist "context" dann wieder der Context vom Fragment. Würde es sicherheitshalber so lassen.

2021-11-06 06:48 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/ProjectOptionsFragment.kt
> +                            val error = validateInput(s.toString(), getContext())
Dann bitte wieder zuurück ändern, jetzt steht "context" drin

2021-11-07 10:25 UTC, juliajulie95 approved these changes

2021-11-07 10:25 UTC, merged