CATROID-1237 REFACTOR SensorLoudness to Kotlin
Catrobat/Catroid pull request #4379
Opened 2021-11-02 14:13 UTC by hofcle78

*Please enter a short description of your pull request and add a reference to the Jira ticket.*
[CATROID-1237 REFACTOR SensorLoudness to Kotlin](https://jira.catrob.at/browse/CATROID-1237)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-01-18 17:56 UTC, gPathpp requested changes
Add some Tests, please.

2022-01-18 17:56 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/soundrecorder/SoundRecorder.java
> +	public void start() throws IOException, IllegalStateException {
This method, is a bit odd, why bother to catch an exception if it's thrown in the same catch clause? 
Please explain your change here :)

2022-01-18 17:56 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/SensorLoudness.kt
> +        private const val MAX_AMP_VALUE = 32_767.0
Refactor to private compile-time constants, please.
https://kotlinlang.org/docs/properties.html#compile-time-constants

2022-01-18 17:56 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/SensorLoudness.kt
> +        private val TAG = SensorLoudness::class.java.simpleName
Make it a private "val" of SensorLoudness to get rid of the companion object, please.

2022-01-18 17:56 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/ui/dialogs/FormulaEditorComputeDialog.java
> +		SensorHandler.stopSensorListeners();
Please explain this change :)

2022-12-30 20:00 UTC, reichli commented
Closed due to inactivity. Can be used as reference by the next developer.

2022-12-30 20:00 UTC, closed without merging