CATROID-1149 import object from local project into current
Catrobat/Catroid pull request #4381
Opened 2021-11-05 15:36 UTC by mseiser

import first actor from local project of choice 
https://jira.catrob.at/browse/CATROID-1149

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-11-12 09:49 UTC, bengaal approved these changes
Looks good to me! We've worked together in PP on this one. On Jenkins there are a few Flaky tests that are failing and a Catroid Language test. The flaky tests are not related and I cannot reproduce the error with the language test locally.

2021-11-14 04:28 UTC, wslany requested changes
I just added a global variable to the project, then added an object that contained the same global variable. This resulted in two global variables with exactly the same name, see screenshot below.
![Screenshot_20211114-050825](https://user-images.githubusercontent.com/1747888/141667285-ad756b46-48ec-41a3-b894-a6b38bb8d793.jpg)

Instead, the two global variables with exactly the same name should be unified to one variable.

Please check with @Tamdav how to handle conflicts, especially also between global and local variables and list names, and also for broadcast messages of the same name (the latter shall be unified to the same message). I believe all of this has already be solved for the case of importing objects from library of share.

It seems that the only way this mistake could appear if this was implemented by using new code (spurious code duplication, with all the ensuing problems), instead of refactoring the existing code so that it can be used for the new case of importing objects from local files as well. Please use best practices of object oriented code without code duplication.

2021-11-17 09:30 UTC, wslany approved these changes

2021-11-17 09:30 UTC, merged

2021-11-17 09:30 UTC, wslany commented
Thanks!