Catroid-94 Incorrect handling of deletion of variables and lists
Catrobat/Catroid pull request #4401
Opened 2021-12-01 17:28 UTC by BeinhAlex

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-12-02 16:14 UTC, DinosaurierRex requested changes
Please have a look at the comments.

2021-12-02 16:14 UTC, DinosaurierRex commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/brickspinner/BrickSpinner.java
> +		/*if (position == -1) {
Please remove comments

2021-12-16 15:35 UTC, DinosaurierRex approved these changes
LGTM now 👍

2021-12-28 15:03 UTC, wslany requested changes
The issue was fixed for global variables and lists, but it still exists for local variables and local lists (available only in the current object) as well as also still for multiplayer variables. Should these be handled in a different ticket? Note that it is more complex for local variables and local lists, since the scope of conflicts is limited to the current object.

Also, it seems that there are some issues with some of the unit tests. As far as I see, they are not being executed on Jenkins, is that correct? If they run through correctly locally, can you please add screenshots? Otherwise, please investigate what the issue could be.

2021-12-29 06:57 UTC, wslany commented
One more case where the "still in use" warning should be shown:
- in the formula editor, tap on "Data" and create a new variable
- tap on the new variable to add it to the formula 
- while still editing the formula, tap again on Data and then delete the variable 
- observe that no warning is shown, the variable is deleted
- when you return to the formula from the Data screen, the variable is still included in the formula.

2022-03-30 15:10 UTC, closed without merging