CATROID-1317 REFACTOR: Unary/BinaryFunction and its interfaces to Kotlin
Catrobat/Catroid pull request #4409
Opened 2021-12-27 17:59 UTC by seopei

https://jira.catrob.at/browse/CATROID-1317

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-12-28 16:13 UTC, gPathpp requested changes

2021-12-28 16:13 UTC, gPathpp commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/function/BinaryFunction.kt
> +    override fun execute(vararg args: Double?): Any? {
Is there a case where null should be returned?
Maybe you find a way to make it more beautiful :)
I think we can simplify the logic :) (one of the executes might not be needed)
Also, have a look at the interface and its implementations maybe we can get rid of some duplicated logic ;)
If possible, use https://play.kotlinlang.org/byExample/05_Collections/05_existential for the nullcheck(s) please ;)

2022-01-14 17:19 UTC, gPathpp approved these changes
Looks **very** good to me :+1:

2022-01-14 21:44 UTC, adnaribo approved these changes

2022-01-14 21:44 UTC, adnaribo commented
Looks good thank you!

2022-01-14 21:49 UTC, merged