CATROID-880 Formula editor buttons for list, text, maths
Catrobat/Catroid pull request #4441
Opened 2022-02-03 13:51 UTC by Piki2000

https://jira.catrob.at/browse/CATROID-880

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-02-03 16:30 UTC, juliajulie95 requested changes

2022-02-03 16:30 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorListsListTest.kt
> +    private val testName: String
Please check why this ios suppressed, could we delete the variable?

2022-02-03 16:30 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorLogicListTest.kt
> +    private val testName: String
Please check why this ios suppressed, could we delete the variable?

2022-02-03 16:30 UTC, juliajulie95 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorTextListTest.kt
> +    private val testName: String
Please check why this is suppressed, could we delete the variable?

2022-02-26 08:45 UTC, juliajulie95 approved these changes
Thank you!

2022-03-17 05:02 UTC, wslany requested changes
Thanks from me as well. Several things that caught my eye and I would like you to correct:

There are several reporters, sensors etc in the new tabs that are shown there, even though the corresponding AI feature has not been activated, and even though they are then correctly not shown in the other, existing categories. For instance, the OCR or voice recognition related sensors should only be shown in the text category when the OCR and/or voice recognition has been turned on in the settings. Here some corresponding screenshots:
![image](https://user-images.githubusercontent.com/1747888/158737374-1ee465dd-033f-41dd-b048-ef10ea9e54aa.png)
![image](https://user-images.githubusercontent.com/1747888/158736364-cac342ea-acbb-423f-8b6c-e41c4d9333c5.png)
![image](https://user-images.githubusercontent.com/1747888/158736444-62bafa62-c1b8-4486-864f-a24d05f61a5b.png)
![image](https://user-images.githubusercontent.com/1747888/158736656-a4ca29bd-1925-4dcd-8fb6-39fb1ae67f71.png)

This implies that there are also missing tests for the AI extension features in the formula editor, because the incorrect visibility of these sensors in the lists under the AI settings should otherwise have been detected.

On the other hand, the following sensor is not listed under Logic when the corresponding AI extension "Object recognition" has been activated by the user (the screenshot is from the sensor list in the formula editor, where it correctly is shown):
![image](https://user-images.githubusercontent.com/1747888/158737684-9ff2438d-ba21-4861-9a52-2d35a7bd22c4.png)

Note: Most of the above was not specified in https://jira.catrob.at/browse/CATROID-880 since at the time when the ticket was written, the settings screen for the AI extension had not yet been introduced, and thus this should be changed even though it was not specified in the ticket. Sorry about that!

For the same reasons, there need to be a few other changes, on the one hand in the order the AI sensors are shown in the lists, and on the other hand, subtitles are needed in the "text" and "logic" lists. These subtitles have already been introduced in the sensors category because of the AI extension since the ticket was written, as follows:

When an AI extension is activated, the corresponding sensors shall be listed _above_ other sensors and reporters in the lists (like it is already done in the existing sensors list), together with subtitles above the corresponding sensors. Here how it looks in the sensor list:
![image](https://user-images.githubusercontent.com/1747888/158738409-b396068e-1d50-438e-92ba-c5cf7b3551e8.png)

So, for instance, when the AI sensors in the new "text" list are shown, they should be preceded by corresponding subtitles (the same as in the sensor category), and these subcategories should be shown at the top instead at the bottom, see below:
![image](https://user-images.githubusercontent.com/1747888/158738953-a1988ee1-5e37-4a13-b837-9c539f533d6f.png)

Same order and subtitles in a similar way also for the sensors in the "logic" list. 

Since there must be some delimiter between the special AI extension sensors and the normal text reporters and functions (since the AI sensors shall be shown _above_ the others), please also introduce a new subtitle called "Other text reporters". This new subtitle shall, however, only be shown when some corresponding AI extensions has been activated that needs to be shown in the text list _above_ the normal text reporters, since otherwise there are no subcategories for text. 

Note that no new subtitle for regular reporters is not needed in the logic list, since there is already a subtitle shown anyway because of the different subcategories of regular logic reporters and constants.  

Also note that no subtitle needs to be shown at the top of the "list" functions, since there are no subcategories.

Please also add corresponding tests in a test-first (test driven) way.

2022-03-17 05:42 UTC, wslany commented
One more question: Why did you change the comparison color here?
![image](https://user-images.githubusercontent.com/1747888/158744595-f2cf0be7-f10e-4908-a307-85734c9f5b75.png)

2023-09-26 15:23 UTC, closed without merging