CATROID-987 Overlapping hints in Formula Editor
Catrobat/Catroid pull request #4443
Opened 2022-02-03 16:34 UTC by friendo97

When hints are enabled, the hint for the scripts is not dismissed yet and the formula editor is opened, the hint for the script hides the lower part of the screen, where hints for the formula editor are shown

https://jira.catrob.at/browse/CATROID-987

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-03-18 10:48 UTC, bengaal approved these changes
Issue is fixed, test is there, Jenkins seems happy; looks good to me!

2022-03-21 20:30 UTC, dandrawes requested changes

2022-03-21 20:30 UTC, dandrawes commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
> +		if (SnackbarUtil.areHintsEnabled(this.getActivity())) {
Please update the header of this file to 2022.

2022-03-21 20:30 UTC, dandrawes commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/hints/HintsShownInCorrectActivityTest.kt
> +
Please add a `tearDown` and restore the initial sharedPreferences.

2022-04-07 14:37 UTC, dandrawes approved these changes
Thank you!

2022-04-07 14:37 UTC, merged