CATROID-810 Fix a few linting errors
Catrobat/Catroid pull request #4501
Opened 2022-04-03 13:52 UTC by l-ilma

Tied to fix a few ignored linting issues. https://jira.catrob.at/browse/CATROID-810

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-07-12 15:23 UTC, juliajulie95 requested changes
As discussed, please have a look :)

2022-07-12 15:23 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java
> +		for (File file : Objects.requireNonNull(sourceDir.listFiles())) {
add nullcheck instead

2022-07-12 15:23 UTC, juliajulie95 commented on catroid/src/main/java/org/catrobat/catroid/io/StorageOperations.java
> +		for (File file : Objects.requireNonNull(dir.listFiles())) {
also here

2022-07-12 18:40 UTC, l-ilma commented
> As discussed, please have a look :)

Please check my changes again 👍

2022-07-13 18:05 UTC, juliajulie95 approved these changes
Approved, thank you! 😄

2022-07-13 18:08 UTC, juliajulie95 commented
Info for reviewers:
I discussed the remaining linting warnings with @l-ilma and tickets for those are already created.
The goal here was to eliminate easier ones 👍

2022-07-20 15:27 UTC, Walcho1125 requested changes
Please look at the remark

2022-07-28 15:44 UTC, l-ilma commented on catroid/config/lint-baseline.xml
> -  -->
@Walcho1125 Oh, since this file was auto-generated I forgot to insert a remark. I fixed this now, can you have another look please?

2022-07-28 15:45 UTC, l-ilma commented
> Please look at the remark

@Walcho1125 Oh, since this file was auto-generated I forgot to insert a remark. I fixed this now, can you have another look please?

2022-07-29 09:39 UTC, Walcho1125 approved these changes
Thanks!

2022-07-29 09:39 UTC, merged