CATROID-1416 "Find/search" in Scripts should ignore trailing spaces
Catrobat/Catroid pull request #4535
Opened 2022-05-06 20:37 UTC by devsebastian

Ticket: https://jira.catrob.at/browse/CATROID-1416

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ]  After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-05-14 11:41 UTC, Walcho1125 requested changes
Looks good to me, however please make sure to update all File headers to "2010-2022"  and that there is only one commit on the PR!

2022-05-17 12:22 UTC, Walcho1125 requested changes

2022-05-17 12:22 UTC, Walcho1125 commented on catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java
> + * Copyright (C) 2010-2022sc The Catrobat Team
please remove the accidently added "sc"

2022-05-18 05:45 UTC, devsebastian commented on catroid/src/androidTest/java/org/catrobat/catroid/test/stage/SearchParameterTest.java
> + * Copyright (C) 2010-2022sc The Catrobat Team
Oops sorry for the mixup. fixed it now

2022-05-18 11:58 UTC, Walcho1125 approved these changes
Looks good!

2022-05-18 12:51 UTC, merged

2022-05-18 12:51 UTC, wslany commented
Thanks!!