CATROID-1391 Cloudflare client certificate implemented
Catrobat/Catroid pull request #4625
Opened 2022-09-10 22:15 UTC by dorianpercic

https://jira.catrob.at/browse/CATROID-1391

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-09-26 14:54 UTC, friendo97 approved these changes
done in PP!

2023-07-07 10:32 UTC, moberer requested changes

2023-07-07 10:32 UTC, moberer commented on cloudflare.properties
Never add a secret key to a git repo.

2023-07-07 10:32 UTC, moberer commented on catroid/src/main/java/org/catrobat/catroid/web/CatrobatWebClient.kt
> +    val keyFactory: KeyFactory = KeyFactory.getInstance("RSA")
Why use RSA?

Prefer elliptic curves! - Faster and more future-proof.

2023-07-07 10:32 UTC, moberer commented on catroid/src/main/java/org/catrobat/catroid/web/CatrobatWebClient.kt
> +    val privateKeyContent = String(privateKeyByteArray, Charset.defaultCharset())
Do not manually mangle around with the key. There has to be a function to import a standard X509 certificate...


==> E.g. use the Java Keystore functionality?

2023-09-26 17:05 UTC, closed without merging