CATROID-1367 Add single undo functionality in datalist
Catrobat/Catroid pull request #4627
Opened 2022-09-18 23:27 UTC by sebastiangollob

Signed-off-by: Sebastian Gollob <sebastiangollob@gmail.com>

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-11-04 10:24 UTC, bengaal approved these changes
Looks good to me! Thank you! :)

2022-11-05 14:52 UTC, mseiser requested changes

2022-11-05 14:52 UTC, mseiser commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java
> +			public List<UserVariable> filterItems(List<UserVariable> all_items) {
Code duplication, doesn't conform to clean code guidelines, please remove duplicated code.

2022-11-05 14:52 UTC, mseiser commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/DataListAdapter.java
> +			public List<UserVariable> filterItems(List<UserVariable> all_items) {
Code duplication

2022-11-05 14:52 UTC, mseiser commented on catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/fragment/DataListFragment.kt
> +            when (lastPerformedAction!!.actionType) {
using !! increases risk of crashing, other ways like using elvis ?: are safer, please change

2023-05-30 10:53 UTC, mseiser approved these changes

2023-05-30 10:53 UTC, merged