CATROID-1421 Extend copy/cut/paste feature across formula editor sessions
Catrobat/Catroid pull request #4631
Opened 2022-09-26 13:21 UTC by friendo97

With this ticket the copy/cut/paste feature is expanded to be persistent across formular editor sessions. This is done by writing the current content of the clipboard to a file called `clipboard.json` on copy and cut. Due to this the clipboard is also available after the app was closed. Whenever a paste happens, the clipboard is either read from a variable or from the file if the variable is not initialized. 

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-09-29 13:45 UTC, bengaal approved these changes
Functionality is implemented and tested. Please adjust the year in that one file but otherwise it looks good to me!

2022-09-29 13:45 UTC, bengaal commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/AdvancedClipboardTest.kt
> + * Copyright (C) 2010-2021 The Catrobat Team
2010 - 2022

2023-07-04 07:46 UTC, moberer requested changes
The main complication here seems to be saving to and loading from a file.

Is this really the approach we want to take here?

a) If we were to drop persistence across reboots, all these changes would collapse into essentially a one-liner. (See https://github.com/Catrobat/Catroid/compare/develop...moberer:Catroid:IDE-178) - Is the added complexity really worth it?

b) Shouldn't we try to actually use the system clipboard and stop rebuilding it slightly differently and with no interoperability?

2023-07-04 07:58 UTC, moberer requested changes

2023-07-04 07:58 UTC, moberer commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/ClipboardManager.kt
Why has the clipboard manager gotten so big? - Beforehand it was just a simple array...

I'm suspecting that the collect and adapt methods could be gotten rid of, if we were to define the allowed states of the data and the interface a bit better.

2023-07-04 07:58 UTC, moberer commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/Clipboard.kt
Unify this with the Clipboard manager and name both Clipboard.

2023-07-25 18:56 UTC, closed without merging

2023-07-25 18:57 UTC, moberer commented
Too complex; Using a simpler implementation;