IDE-59 fixed toMetricUnitRepresentation
Catrobat/Catroid pull request #4696
Opened 2023-02-22 10:57 UTC by Aayush2111

Jira ticket: https://jira.catrob.at/browse/IDE-59

Fixed toMetricUnitRepresentation by changing Integer to Double

Before changes:
![image](https://user-images.githubusercontent.com/85586404/220600737-11afd218-78ff-42c9-a7a9-69d9b8db8fe5.png)

After changes:
![WhatsApp Image 2023-02-22 at 16 26 45](https://user-images.githubusercontent.com/85586404/220600676-0a67cc7f-9c6f-4a48-8a88-98a6ce9444af.jpg)

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-02-22 11:12 UTC, Aayush2111 commented
@mseiser @sebastiangollob 
This bug was caused by the use of integers instead of doubles in the representation of units, which led to unexpected results.

To fix the bug, I have made the necessary changes to our code to ensure that all unit representations are now stored as doubles.

kindly review and move the ticket accordingly, thankyou! :)

2023-02-25 02:17 UTC, sebastiangollob requested changes
https://github.com/Catrobat/Catroid/pull/4703#pullrequestreview-1314434743

2023-03-08 15:19 UTC, sebastiangollob approved these changes

2023-03-28 10:41 UTC, Aayush2111 commented
> please add a testcase that confirms the correct behavior, to make sure that we catch unwanted changes in regards to this in the future

Done! I have changed the tests parameters and all of them are passing locally.

2023-09-27 19:49 UTC, closed without merging