IDE 104 Refactor WebconnectionException to kotlin
Catrobat/Catroid pull request #4715
Opened 2023-03-06 18:03 UTC by Aayush2111

Jira ticket: https://jira.catrob.at/browse/IDE-104

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-03-21 01:00 UTC, sebastiangollob requested changes
e.g. use

```
class WebconnectionException(val statusCode: Int, message: String?) : Exception(message) {
    constructor(statusCode: Int) : this(statusCode, "Unknown Error, no exception message given.")
```

2023-03-21 20:37 UTC, Aayush2111 commented
@sebastiangollob done! Thanks for the suggestions!
I also renamed the 'WebconnectionException' class to 'WebConnectionException' to follow standard naming conventions for class names in Kotlin.

2024-02-09 09:27 UTC, ma-zea commented
please resolve build issues

2026-05-12 22:54 UTC, harshsomankar123-tech commented
Done #4956

2026-05-12 22:54 UTC, closed without merging