Refactored ScratchDataFetcher
Catrobat/Catroid pull request #4728
Opened 2023-03-14 16:04 UTC by Samrj12

Refactored ScratchDataFetcher from Java to Kotlin

https://jira.catrob.at/browse/IDE-147?filter=-2

- [X ] Include the name of the Jira ticket in the PR’s title
- [X ] Include a summary of the changes plus the relevant context
- [X ] Choose the proper base branch (*develop*)
- [X ] Confirm that the changes follow the project’s coding guidelines
- [X ] Verify that the changes generate no compiler or linter warnings
- [X ] Perform a self-review of the changes
- [X ] Verify to commit no other files than the intentionally changed ones
- [X ] Include reasonable and readable tests verifying the added or changed behavior
- [X ] Confirm that new and existing unit tests pass locally
- [X ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X ] Stick to the project’s gitflow workflow
- [X ] Verify that your changes do not have any conflicts with the base branch
- [X ] After the PR, verify that all CI checks have passed
- [X ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-03-21 01:09 UTC, sebastiangollob requested changes

2023-03-21 01:09 UTC, sebastiangollob commented on catroid/src/test/java/org/catrobat/catroid/test/web/CatrobatWebClientTest.kt
> +    private var requestMock: Request? = null
use `lateinit` for non-null properties that will be initialized later. This way, you can avoid using nullable types and the not-null assertion operator (!!)

```suggestion
    private lateinit var requestMock: Request
```

2023-03-21 01:09 UTC, sebastiangollob commented on catroid/src/test/java/org/catrobat/catroid/test/web/CatrobatWebClientTest.kt
> +    private var clientMock: OkHttpClient? = null
```suggestion
    private lateinit var clientMock: OkHttpClient
```

2023-03-21 01:09 UTC, sebastiangollob commented on catroid/src/test/java/org/catrobat/catroid/test/web/CatrobatWebClientTest.kt
> +    private var call: Call? = null
```suggestion
    private lateinit var call: Call
```

2023-03-21 01:09 UTC, sebastiangollob commented on catroid/src/test/java/org/catrobat/catroid/test/web/CatrobatWebClientTest.kt
> +        Mockito.`when`(clientMock!!.newCall(requestMock)).thenReturn(call)
```suggestion
        Mockito.`when`(clientMock.newCall(requestMock)).thenReturn(call)
```

2023-03-21 19:29 UTC, Samrj12 commented
@sebastiangollob Thank you for the feedback. I have committed the changes.

2023-03-21 20:12 UTC, sebastiangollob requested changes
I oversaw one thing: please fix the **Static Analysis** warnings shown in the pipeline :)

2023-03-24 20:38 UTC, Samrj12 commented
@sebastiangollob I have made the new changes.

2025-05-02 09:08 UTC, closed without merging