IDE-116 Visualize the color code in formulas
Catrobat/Catroid pull request #4906
Opened 2023-11-23 18:15 UTC by Jr9992

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-12-15 12:52 UTC, ma-zea requested changes
good start, there are some inconsistencies when importing certain methods and a minor mistake

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +    val projectManager: ProjectManager by KoinJavaComponent.inject(ProjectManager::class.java)
import org.koin.java.KoinJavaComponent.inject and then just use inject(ProjectManager::class.java)

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +        Espresso.pressBack()
import it properly so you can just use pressBack()

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +            .check(matches(ViewMatchers.withText("'#0074CD ' ")))
import properly to just use withText(...)

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +        Espresso.pressBack()
again import properly to just call function

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +            .check(matches(ViewMatchers.withText("'#0074CD ' or '#CA0186 ' ")))
again import properly to just call function

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +        Espresso.closeSoftKeyboard()
again import properly to just call function

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +        onView(ViewMatchers.withText(R.string.color_picker_apply))
again import properly to just call function

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorColorVisualizeTest.kt
> +        ColorPickerInteractionWrapper.onColorPickerPresetButton(row, column)
again import properly to just call function, function name alone is sufficient to know what this is about

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/main/java/org/catrobat/catroid/content/bricks/FormulaBrick.java
> +					FormulaSpannableStringBuilder.INSTANCE.buildSpannableFormulaString(view.getContext(), text,
remove '.INSTANCE', you will see the reason in the FormulaSpannableStringBuilder!

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaSpannableStringBuilder.kt
> +    fun buildSpannableFormulaString(context: Context, formulaString: String, textSize: Float):
add '@JvmStatic' above the method declaration, see kotlin documentation for further details!

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/main/java/org/catrobat/catroid/formulaeditor/FormulaEditorEditText.java
> +				FormulaSpannableStringBuilder.INSTANCE.buildSpannableFormulaString(context,
remove '.INSTANCE', see comment in FormulaSpannableStringBuilder

2023-12-15 12:52 UTC, ma-zea commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java
> +				FormulaSpannableStringBuilder.INSTANCE.buildSpannableFormulaString(this.getContext(),
remove '.INSTANCE'

2024-09-11 11:25 UTC, edonmucaj approved these changes

2024-09-11 11:25 UTC, merged