IDE-235 Language change confirmation
Catrobat/Catroid pull request #4985
Opened 2024-05-02 13:23 UTC by hannesweilharter

In the language settings the user now has to confirm the selected language, and thus it's not possible anymore to accidentially change the app to a language the user doesn't understand.

- new Confirm button in the language settings
- new class `LanguageSettingListPreference` - derived from `ListPreference`

https://catrobat.atlassian.net/browse/IDE-235

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-05-10 06:52 UTC, Jr9992 requested changes

2024-05-10 06:52 UTC, Jr9992 commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/formulaeditor/FormulaEditorTouchesActorOrObjectTest.kt
> +        openActionBarOverflowOrOptionsMenu(getInstrumentation().targetContext)
Use openActionBarMenu() from UiTestUtils instead.

2024-05-13 16:00 UTC, Jr9992 approved these changes

2026-04-16 14:05 UTC, harshsomankar123-tech commented
@hannesweilharter could you please resolve the conflicts? Once that’s done, we can proceed with the review.

2026-04-17 10:14 UTC, hannesweilharter commented
@harshsomankar123-tech all conflicts are resolved.
A lot of functions used in the `LanguageSettingsListPreference` and `SettingsFragment` are deprecated. Perhaps we should create a follow-up ticket for refactoring. WDTY?

2026-04-20 20:14 UTC, harshsomankar123-tech reviewed
@hannesweilharter Thanks for the PR! I tested it locally and the UI works perfectly. I have a few concerns could you please take a look?

2026-04-20 20:14 UTC, harshsomankar123-tech commented on catroid/src/main/java/android/preference/LanguageSettingListPreference.kt
> +package android.preference
The class is currently placed under the android.preference package, which belongs to the Android framework and shouldn’t be used for app code. It would be better to move it to org.catrobat.catroid.ui.settings to keep things properly organized and avoid any potential conflicts with future Android updates.

2026-04-20 20:14 UTC, harshsomankar123-tech commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/LanguagePickerTest.java
> +		onData(PreferenceMatchers.withTitle(R.string.preference_title_language)).perform(click());
why we change it  ? Plz explain?
 From my side it is right becoz Replacing the Arabic test with a French test removes validation for Right-to-Left (RTL) layouts. The confirmation dialog's appearance and behavior should be specifically verified in RTL mode.WDYT

2026-04-20 20:14 UTC, harshsomankar123-tech commented on catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/ui/activity/rtl/LanguagePickerTest.java
>  }
its a minor change but we can add a test case testCancelLanguageChange that selects a new language in the picker, clicks "Cancel," and verifies that the app language remains the same.

2026-04-20 20:14 UTC, harshsomankar123-tech commented on catroid/src/main/java/android/preference/LanguageSettingListPreference.kt
> +            val selectedLanguageTag = entryValues[mClickedDialogEntryIndex].toString()
This line will cause the app to crash with an ArrayIndexOutOfBoundsException if mClickedDialogEntryIndex is -1.
This happens if getValueIndex() (called on line 45) returns -1 because the current value is null or not found in the list.Please add a safety check like that:
```
if (mClickedDialogEntryIndex >= 0) {
    val selectedLanguageTag = entryValues[mClickedDialogEntryIndex].toString()
    if (callChangeListener(selectedLanguageTag)) {
        value = selectedLanguageTag
    }
}
```

2026-04-24 10:00 UTC, wslany commented
This way to do it, with a dialog, is a UX mistake. The "normal" path should never have to be confirmed. There should be a way to recover, or to undo, but most users will do this *intentionally`* and should therefore not be bothered with a confirmation dialog.

2026-04-24 10:00 UTC, closed without merging