CATROID-1071 GoToRandomPositionAction refactor
Catrobat/Catroid pull request #5052
Opened 2024-11-12 12:32 UTC by erikcoxx98

Refactor GoToRandomPositionAction.java and GoToRandomPositionActionTest.java to Kotlin - Ticket 1071

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Branch-and-Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-11-15 14:15 UTC, JayTropper commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/GoToRandomPositionActionTest.kt
> +    private var sprite: Sprite? = null
I would prefer, if all the three variables would be initialized with the `lateinit` key word as follows:
```suggestion
    private lateinit var sprite: Sprite
```
Gives the code a cleaner look, since we you can then remove all the `!!` operators from the method calls.

2024-11-15 14:15 UTC, JayTropper commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/GoToRandomPositionActionTest.kt
> +        Assert.assertEquals(0f, sprite!!.look.xInUserInterfaceDimensionUnit)
Please replace all `Assert.assertEquals()` with the simple `assertEquals()` from `junit.framework.TestCase.assertEquals`, since it is deprecated.

2024-11-27 10:33 UTC, JayTropper requested changes

2024-11-27 10:33 UTC, JayTropper commented on catroid/src/main/java/org/catrobat/catroid/content/actions/GoToRandomPositionAction.kt
> + * Copyright (C) 2010-2022 The Catrobat Team
Can you just update this to 2010-202**4**.  Please also update the year for every file you change in the future :)

2024-11-27 10:33 UTC, JayTropper commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/GoToRandomPositionActionTest.kt
> + * Copyright (C) 2010-2022 The Catrobat Team
Here as well please

2024-11-27 10:33 UTC, JayTropper commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/GoToRandomPositionActionTest.kt
> +    private lateinit var  dummySprite: Sprite
```suggestion
    private lateinit var dummySprite: Sprite
```
There is just one space that needs to be removed.

2024-11-27 10:33 UTC, JayTropper commented on catroid/src/test/java/org/catrobat/catroid/test/content/actions/GoToRandomPositionActionTest.kt
> +    private lateinit var  action: GoToRandomPositionAction
Here as well

2024-12-06 16:24 UTC, JayTropper approved these changes
Looks good to me

2026-03-23 10:50 UTC, dorianpercic approved these changes

2026-03-23 10:50 UTC, dorianpercic commented on catroid/src/main/java/org/catrobat/catroid/content/actions/GoToRandomPositionAction.kt
> +        sprite!!.look.setPositionInUserInterfaceDimensionUnit(randomXPosition, randomYPosition)
Please get rid of "not-null assert" operators. Try to use safe calls with "?" or with the "let" for scoped null checks. Please do this also for the test.

2026-03-23 10:50 UTC, merged